In [1]:
import os
import sys
sys.path.append("/home/zhangsd/repos/CF-BGAP")
import pandas as pd
import numpy as np
from pathlib import Path
import shutil
from GCMC.gcmc_process import create_tasks, run_and_check_pre_tasks
from GCMC.utils import run_simulation

from GCMC.utils import process_isotherm_results, process_heat_results
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde
from sklearn import metrics

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.

## GCMC results

In [2]:

n_jobs = 64
gases = ["CO2", "N2"]
for temp in [298.0, 323.0, 473.0]:
    dataset = f"stable_coremof_4606_mc{temp}K"
    # dataset = "stable_coremof_4606_mc473.0K.0K"
    gcmc_workdir = Path(f"CGCNN_MT/inference/CoREMOF2019/{dataset}/mc_data")
    result_dir = gcmc_workdir
    ads_dfs = []
    for batch_dir in gcmc_workdir.glob("*"):
        if not batch_dir.is_dir():
            continue
        batch_name = batch_dir.name
        df_ads = process_isotherm_results(batch_dir, gases, unit="mol/kg", verbose=0, n_jobs=n_jobs)
        if len(df_ads) > 0:
            ads_dfs.append(df_ads)
    if len(ads_dfs) == 0:
        continue
    df_ads = pd.concat(ads_dfs, ignore_index=True)
    print("number of isotherm data points: ", len(df_ads))
    if len(df_ads) > 0:
        df_ads.to_csv(result_dir/(f'00-isotherm-data-{dataset}.tsv'), index=False, sep='\t', float_format='%.7f')
# df_ads = process_isotherm_results(gcmc_workdir, gases, unit="mol/kg", verbose=0, n_jobs=n_jobs)
# print("number of isotherm data points: ", len(df_ads))
# if len(df_ads) > 0:
#     df_ads.to_csv(result_dir/(f'00-isotherm-data-{dataset}.tsv'), index=False, sep='\t', float_format='%.6f')

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/LULXOG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LULXOG_clean_3.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/IWEWEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEWEO_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/IWEWEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEWEO_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/LULXOG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LULXOG_clean_3.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/ja500330a_si_006_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja500330a_si_006_auto_1.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/ja500330a_si_006_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja500330a_si_006_auto_1.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/XIGHIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIGHIF_clean_2.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/XIGHIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIGHIF_clean_2.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/LABPIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPIQ_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/LABPIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPIQ_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/BEPWEA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BEPWEA_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/BEPWEA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_BEPWEA_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/XEVGUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XEVGUC_clean_1.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/REXDUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDUV_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/REXDUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDUV_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch28/XEVGUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XEVGUC_clean_1.1.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/ULAQAB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/EZIMEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/EZIMEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/LUDVIP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVIP_clean_2.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/FAVDAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDAK_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/LUDVIP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVIP_clean_2.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/FAVDAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDAK_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/KACGED_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KACGED_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch25/KACGED_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KACGED_clean_1.2.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/RAHNUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/RAHNUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/XAFNOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAFNOH_clean_4.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/SOHNIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNIN_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/SOHNIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNIN_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/XAFNOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAFNOH_clean_4.3.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/ULOKEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKEN_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/ULOKEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKEN_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/LABPUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPUC_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/LABPUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPUC_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/IMISIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IMISIH_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch38/IMISIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IMISIH_clean_2.2.2_298.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/SOHNAF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNAF_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/SOHNAF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNAF_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/ZOQTIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQTIK_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/ZOQTIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQTIK_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/IPEBEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IPEBEM_clean_1.1.4_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/IPEBEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IPEBEM_clean_1.1.4_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/GUVKUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUVKUE_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/GUVKUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUVKUE_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/ECALIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ECALIF_clean_4.1.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch19/ECALIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ECALIF_clean_4.1.2_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/RUYKAZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/RUYKAZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/RONSOC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/RONSOC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/WEYQAU02_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/WEYQAU02_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/GOYXUP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/GOYXUP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/TOLGOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/TOLGOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/NURMUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/NURMUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/IVOCON_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/IVOCON_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/ITAPAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/ITAPAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/jacs.6b08724_ja6b08724_si_010_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/jacs.6b08724_ja6b08724_si_010_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/NIRKAB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/NIRKAB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/OGIBOV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/OGIBOV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/DUNXUH15_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/DUNXUH15_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/OXITOF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/OXITOF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/XAMDUM06_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/XAMDUM06_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/ATIXUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/ATIXUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/LIQJEC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIQJEC_clean_2.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/LIQJEC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIQJEC_clean_2.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/ULOMAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOMAL_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/ULOMAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOMAL_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/ic403134c_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ic403134c_si_002_clean_5.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/ic403134c_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ic403134c_si_002_clean_5.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/LUDVUB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVUB_clean_1.1.4_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/LUDVUB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVUB_clean_1.1.4_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/REXDOP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDOP_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/REXDOP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDOP_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/REXCOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCOO_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/REXCOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCOO_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/VIWZOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIWZOR_clean_3.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch45/VIWZOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIWZOR_clean_3.2.2_298.000000_100000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/RUDQEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/MARLAS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/MARLAS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/BUVYIB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/BUVYIB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/LEMHAM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/LEMHAM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/REXDEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDEF_clean_2.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/MIVPAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MIVPAJ_clean_4.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/REXDEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDEF_clean_2.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/MIVPAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MIVPAJ_clean_4.3.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/XAKVUB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAKVUB_clean_3.3.4_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/IHILUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IHILUI_clean_4.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/IHILUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IHILUI_clean_4.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/XIPBOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIPBOO_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/UZUXOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UZUXOE_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/UZUXOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UZUXOE_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/XIPBOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIPBOO_clean_2.2.2_298.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/WUDZOM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZOM_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/WUDZOM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZOM_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/XUNGOD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNGOD_clean_5.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch35/XUNGOD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNGOD_clean_5.3.2_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/ZAZNUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/ZAZNUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/MAKHAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/MAKHAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/CUWWEY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/CUWWEY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/UQERIT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/UQERIT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/TUMDAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/TUMDAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/LABNIO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/LABNIO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/SIQFED_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/SIQFED_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/QETHUT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/QETHUT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/LABPOW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPOW_clean_2.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/SOHMUY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMUY_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/SOHMUY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMUY_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/LABPOW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPOW_clean_2.2.1_298.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/YAHWAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_YAHWAI_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/YAHWAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_YAHWAI_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/XEVHEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XEVHEN_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/XEVHEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XEVHEN_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/POBNEA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POBNEA_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/UZUTUG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UZUTUG_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/UZUTUG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UZUTUG_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch2/POBNEA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POBNEA_clean_2.2.2_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/XIJJEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/XIJJEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/XAQMOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/XAQMOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/IKUBUL01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/IKUBUL01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/IBAQAF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/IBAQAF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/TIZVIH01_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/TIZVIH01_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/IBIYOI_ion_b/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IBIYOI_ion_b_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/IBIYOI_ion_b/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IBIYOI_ion_b_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/EBEXEQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXEQ_clean_3.3.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/EBEXEQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXEQ_clean_3.3.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/UCOJAZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJAZ_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/UCOJAZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJAZ_clean_2.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/jacs.5b12516_ja5b12516_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_003_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/jacs.5b12516_ja5b12516_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_003_clean_2.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/LIXMIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXMIQ_clean_3.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/acs.inorgchem.6b02407_ic6b02407_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_002_clean_3.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/acs.inorgchem.6b02407_ic6b02407_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_002_clean_3.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch32/LIXMIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXMIQ_clean_3.2.2_298.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch8/QUSBEM_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUSBEM_charged_5.3.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch8/QUSBEM_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUSBEM_charged_5.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch8/ORAGEU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ORAGEU_clean_3.3.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch8/ORAGEU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ORAGEU_clean_3.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch8/ULOKUD01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKUD01_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch8/FAVDEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDEO_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch8/ULOKUD01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKUD01_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch8/FAVDEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDEO_clean_1.2.1_298.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/ULOLUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLUE_clean_1.1.4_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/ULOLUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLUE_clean_1.1.4_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/ic5b00096_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ic5b00096_auto_1.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/ic5b00096_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ic5b00096_auto_1.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/COQJID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_COQJID_clean_3.1.3_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/COQJID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_COQJID_clean_3.1.3_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/JALTUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JALTUL_clean_2.3.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/JALTUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JALTUL_clean_2.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/ZITRUP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZITRUP_clean_3.3.3_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/ZITRUP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZITRUP_clean_3.3.3_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/XIGHEB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIGHEB_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch34/XIGHEB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIGHEB_clean_1.2.1_298.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/SACDUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SACDUX_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/SACDUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SACDUX_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/HAPBEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HAPBEI_clean_3.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/HAPBEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HAPBEI_clean_3.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/IYOCIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IYOCIK_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/IYOCIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IYOCIK_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/TURBUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TURBUE_clean_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/TURBUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TURBUE_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/VUHMOC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHMOC_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch15/VUHMOC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHMOC_clean_1.2.1_298.000000_10000.dataNo valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch4/RUBLEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch4/RUBLEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch4/cg501730q_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_cg501730q_si_002_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch4/cg501730q_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_cg501730q_si_002_clean_2.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch4/HOYREU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYREU_clean_2.2.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch4/HOYREU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYREU_clean_2.2.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch4/ja512311a_si_003_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512311a_si_003_auto_1.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch4/ja512311a_si_003_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512311a_si_003_auto_1.1.1_298.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/ZUCKIT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/ZUCKIT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/CIXBUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIXBUH_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/CIXBUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIXBUH_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/ENAFOP_ion_b/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ENAFOP_ion_b_2.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/ENAFOP_ion_b/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ENAFOP_ion_b_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/XAPDAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPDAU_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/XAPDAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPDAU_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/GUVLAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUVLAL_clean_2.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/GUVLAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUVLAL_clean_2.1.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/OVADAR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OVADAR_clean_4.4.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/OVADAR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OVADAR_clean_4.4.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/SOXHUI_SL/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOXHUI_SL_2.2.5_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/SOXHUI_SL/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOXHUI_SL_2.2.5_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/PORLEP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_PORLEP_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/PORLEP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_PORLEP_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/FUBDEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FUBDEM_clean_2.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch18/FUBDEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FUBDEM_clean_2.1.1_298.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/JOHSIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/WOBCIB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/WOBCIB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/WEFZIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/WEFZIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/VEJYUF02_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/VEJYUF02_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/YUYBIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/YUYBIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/UMABIV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/UMABIV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/NIVWIY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NIVWIY_clean_6.4.4_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/NIVWIY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NIVWIY_clean_6.4.4_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/ISUGIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ISUGIN_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/YEZSEC01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_YEZSEC01_clean_1.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/ISUGIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ISUGIN_clean_2.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/YEZSEC01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_YEZSEC01_clean_1.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/VAKPUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKPUV_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/AHOKIR01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AHOKIR01_clean_6.5.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/VAKPUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKPUV_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/ICITUK_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ICITUK_charged_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/ICITUK_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ICITUK_charged_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/LUDVEL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVEL_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch39/LUDVEL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVEL_clean_1.2.1_298.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/HORHIG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/HORHIG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/MANLIX_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/MANLIX_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/HUYKUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/HUYKUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/ECASAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/ECASAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/SEHMUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SEHMUO_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/UDAWUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAWUU_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/UDAWUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAWUU_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/SEHMUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SEHMUO_clean_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/HAPBAE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HAPBAE_clean_3.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/HAPBAE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HAPBAE_clean_3.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/TISWEZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TISWEZ_clean_3.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/TISWEZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TISWEZ_clean_3.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/OTIBUQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OTIBUQ_clean_1.4.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/ZEZPIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZEZPIF_clean_2.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/ZEZPIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZEZPIF_clean_2.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/FANDEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FANDEG_clean_3.3.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/FANDEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FANDEG_clean_3.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/GOYXID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GOYXID_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch13/GOYXID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GOYXID_clean_3.3.2_298.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/ADASOP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/RIFQEC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/RIFQEC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/EMODOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/EMODOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/GUJGAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/GUJGAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/cm303749m_si_001_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/cm303749m_si_001_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/GARTAX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GARTAX_clean_3.3.3_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/RIYBEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBEI_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/GARTAX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GARTAX_clean_3.3.3_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/WODWUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WODWUJ_clean_3.3.3_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/RIYBEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBEI_clean_2.1.1_298.000000_10000.data



Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/WODWUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WODWUJ_clean_3.3.3_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/POKVAO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POKVAO_clean_5.3.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/POKVAO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POKVAO_clean_5.3.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/VOZVIR01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVIR01_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/VOZVIR01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVIR01_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/HABCEV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HABCEV_clean_1.1.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/HABCEV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HABCEV_clean_1.1.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/RIYBIM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBIM_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/RIYBIM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBIM_clean_2.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/QESYOD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QESYOD_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/QESYOD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QESYOD_clean_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/VUHPUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHPUL_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/VUHPUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHPUL_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/ULOLEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLEO_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch20/ULOLEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLEO_clean_1.2.1_298.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/XOMJOY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XOMJOY_clean_3.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/XOMJOY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XOMJOY_clean_3.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/WUDZUS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZUS_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/WUDZUS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZUS_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/XIGHAX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIGHAX_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/XIGHAX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIGHAX_clean_2.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/XUNHAQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNHAQ_clean_5.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/XUNHAQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNHAQ_clean_5.3.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/CUVHIL02_clean_h/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL02_clean_h_3.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/CUVHIL02_clean_h/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL02_clean_h_3.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/LABPEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPEM_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch26/LABPEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPEM_clean_1.2.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/IMUKUW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/IMUKUW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/AMUWIP_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AMUWIP_charged_2.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/ja512973b_si_002_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_002_auto_2.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/LIKCOY_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIKCOY_charged_2.2.2_298.000000_10000.data



Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/AGABIU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AGABIU_clean_2.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/AGABIU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AGABIU_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/AMUWIP_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AMUWIP_charged_2.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/ja512973b_si_002_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_002_auto_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/LIKCOY_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIKCOY_charged_2.2.2_298.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/ZIHTEP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZIHTEP_clean_4.3.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/ZIHTEP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZIHTEP_clean_4.3.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/LABNOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNOU_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/LABNOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNOU_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/WUDYUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDYUR_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/CIXCAO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIXCAO_clean_2.1.1_298.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/CIXCAO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIXCAO_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/WUDYUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDYUR_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/LABQAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABQAJ_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch21/LABQAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABQAJ_clean_1.2.1_298.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/UCOJED_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJED_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/NIFZOT_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NIFZOT_charged_2.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/NIFZOT_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NIFZOT_charged_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/UCOJED_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJED_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/NARPAA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NARPAA_clean_3.2.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/NARPAA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NARPAA_clean_3.2.3_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/UVUQOT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UVUQOT_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/NEGMUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NEGMUI_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/NEGMUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NEGMUI_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/UVUQOT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UVUQOT_clean_1.2.1_298.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/CAYMIZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAYMIZ_clean_4.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/CAYMIZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAYMIZ_clean_4.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/HOYRIY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYRIY_clean_2.2.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch6/HOYRIY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYRIY_clean_2.2.3_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/RIVDEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/RIVDEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/ja512973b_si_004_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_004_auto_1.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/ja512973b_si_004_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_004_auto_1.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/KACGAZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KACGAZ_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/KACGAZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KACGAZ_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/REXCEE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCEE_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/REXCEE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCEE_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/GEVXIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GEVXIQ_clean_3.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/GEVXIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GEVXIQ_clean_3.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/WUDZIG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZIG_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch29/WUDZIG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZIG_clean_1.2.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/XEZRIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/TOJVIZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/TOJVIZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/CAGSAG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/CAGSAG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/TEQWER_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/TEQWER_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/DAMDUT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DAMDUT_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/DAMDUT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DAMDUT_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/LUDTUZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDTUZ_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/LABNEK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNEK_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/CAKFEB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAKFEB_clean_3.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/VAKPOP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKPOP_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/CAKFEB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAKFEB_clean_3.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/LUDTUZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDTUZ_clean_1.2.1_298.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/LABNEK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNEK_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/VAKPOP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKPOP_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/UCOJIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJIH_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/UCOJIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJIH_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/JOVWOI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JOVWOI_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/VUHPOF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHPOF_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch40/VUHPOF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHPOF_clean_1.2.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/ESUMOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/RAKDEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAKDEN_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/RAKDEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAKDEN_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/BUPFEY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BUPFEY_clean_1.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/BUPFEY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_BUPFEY_clean_1.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/RAKDAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAKDAJ_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/RAKDAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAKDAJ_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/LABMUZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABMUZ_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/SOMCON_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOMCON_clean_2.1.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/LABMUZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABMUZ_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/SOMCON_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOMCON_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/JEDJUY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JEDJUY_clean_4.3.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/JEDJUY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JEDJUY_clean_4.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/CIPLIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIPLIX_clean_2.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/VIZSOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZSOO_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/VIZSOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZSOO_clean_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/CIPLIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIPLIX_clean_2.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/REXCUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCUU_clean_2.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/REXCUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCUU_clean_2.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/QOGGID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOGGID_clean_4.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch7/QOGGID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOGGID_clean_4.2.2_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/OCUNAC_manual/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/OCUNAC_manual/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/QETCUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/QETCUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/QAVYUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/QAVYUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/SOHMEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/SOHMEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/REXFOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFOR_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/REXFOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFOR_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/POFGUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POFGUO_clean_2.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/POFGUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POFGUO_clean_2.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/RUBTAK03_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RUBTAK03_auto_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/RUBTAK03_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RUBTAK03_auto_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/UTOCAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UTOCAJ_clean_3.3.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/CEDFIC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CEDFIC_clean_3.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/UTOCAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UTOCAJ_clean_3.3.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/CEDFIC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CEDFIC_clean_3.3.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/DOGMET_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DOGMET_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch37/DOGMET_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DOGMET_clean_3.3.2_298.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/REXDAB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDAB_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/EBEXIU02_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXIU02_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/REXDAB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDAB_clean_2.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/GEGBOL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GEGBOL_clean_2.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/EBEXIU02_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXIU02_clean_3.3.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/GEGBOL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GEGBOL_clean_2.1.1_298.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/FOFMOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FOFMOE_clean_3.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/FOFMOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FOFMOE_clean_3.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/OSIKIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OSIKIL_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/OSIKIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OSIKIL_clean_2.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/DEFRIR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DEFRIR_clean_3.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/RIYBOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBOS_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/DEFRIR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DEFRIR_clean_3.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/RIYBOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBOS_clean_2.1.1_298.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/ja512311a_si_007_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512311a_si_007_auto_1.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch14/ja512311a_si_007_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512311a_si_007_auto_1.1.1_298.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/LAFRAN01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/LAFRAN01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/XEGKUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XEGKUR_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/XEGKUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XEGKUR_clean_2.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/ULOJUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOJUC_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/JOVROD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JOVROD_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/ULOJUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOJUC_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/jacs.5b12516_ja5b12516_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_002_clean_2.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/jacs.5b12516_ja5b12516_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_002_clean_2.2.2_298.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/JOVROD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JOVROD_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/RIHXIR_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIHXIR_charged_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch44/RIHXIR_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIHXIR_charged_2.2.2_298.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/ja407778a_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/ja407778a_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/OJUNIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/OJUNIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/WEHJOK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/WEHJOK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/FAVKET_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/FAVKET_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/XAPDEY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPDEY_clean_2.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/XAPDEY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPDEY_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/ZISXEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISXEG_clean_2.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/REXFUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFUX_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/HUCBAJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HUCBAJ_charged_3.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/HUCBAJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HUCBAJ_charged_3.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/ZISXEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISXEG_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/REXFUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFUX_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/REXCII_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCII_clean_2.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/REXCII_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCII_clean_2.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/acs.inorgchem.6b02407_ic6b02407_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_003_clean_2.2.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/acs.inorgchem.6b02407_ic6b02407_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_003_clean_2.2.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/CUVHIL_clean_h/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL_clean_h_3.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/CUVHIL_clean_h/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL_clean_h_3.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/ja507947d_si_001_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja507947d_si_001_auto_1.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/ja507947d_si_001_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja507947d_si_001_auto_1.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/GUSCIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUSCIH_clean_3.3.3_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch31/GUSCIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUSCIH_clean_3.3.3_298.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/VUJBOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/VUJBOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/KETHEY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/KETHEY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/NERVEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/NERVEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/j.jssc.2016.09.008_mmc8_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/j.jssc.2016.09.008_mmc8_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/QUXRAE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/QUXRAE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/LEDJUA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/LEDJUA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/JOBFEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/JOBFEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/VUHPAR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/VUHPAR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/KEQYOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/KEQYOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/COLPEA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/COLPEA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/cg5010616_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/cg5010616_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/LABQEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/LABQEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/cg5010616_si_007_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/cg5010616_si_007_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/MODNAU_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/MODNAU_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/XESLAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/XESLAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/QIXNES_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/QIXNES_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/ic5011133_si_004_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/ic5011133_si_004_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/BEXTUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/BEXTUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/ICODIP01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/ICODIP01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/CAJVUG_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/CAJVUG_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/QARLON_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QARLON_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/SARMII_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SARMII_clean_2.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/LAKFIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LAKFIN_clean_2.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/VUHNIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNIX_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/LAKFIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LAKFIN_clean_2.1.1_298.000000_100000.data



Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/MEXJAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MEXJAC_clean_2.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/MEXJAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MEXJAC_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/SARMII_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SARMII_clean_2.2.2_298.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/QARLON_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QARLON_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/VUHNIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNIX_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/SUXGUP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SUXGUP_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/SUXGUP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SUXGUP_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/QOJTUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOJTUE_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/QOJTUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOJTUE_clean_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/VOZVAJ01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVAJ01_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/VOZVAJ01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVAJ01_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/ZOQSUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQSUV_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch12/ZOQSUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQSUV_clean_1.2.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/XITYEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/XITYEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/SALZAH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/AFEJOK_ion_b/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/AFEJOK_ion_b/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/LAPLOG01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/LAPLOG01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/IFAGON_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/IFAGON_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/FONQIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/FONQIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/KOHLIE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/KOHLIE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/BOYTEQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/BOYTEQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/OJOZOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OJOZOE_clean_5.4.3_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/OJOZOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OJOZOE_clean_5.4.3_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/TEJGEW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TEJGEW_clean_3.3.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/TEJGEW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TEJGEW_clean_3.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/DOMGAP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DOMGAP_clean_1.1.3_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/DOMGAP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DOMGAP_clean_1.1.3_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/QARMAA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QARMAA_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/QARMAA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QARMAA_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/AKUHOD01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AKUHOD01_clean_4.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch10/AKUHOD01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AKUHOD01_clean_4.3.3_298.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/OKUJUB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/OKUJUB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/FITJAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/GONSUZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/GONSUZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/SUKNOC_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/SUKNOC_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/c5ta10401g_c5ta10401g2_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/c5ta10401g_c5ta10401g2_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/WEYQAU04_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/WEYQAU04_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/CICSOW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/CICSOW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/AQOMAW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/AQOMAW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/QOJVAM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOJVAM_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/QOJVAM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOJVAM_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/ZISYAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISYAD_clean_4.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/ZISYAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISYAD_clean_4.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/LOCNIB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LOCNIB_clean_3.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/LOCNIB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LOCNIB_clean_3.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/ja500330a_si_009_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja500330a_si_009_auto_1.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/ja500330a_si_009_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja500330a_si_009_auto_1.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/IFEPIT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IFEPIT_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/IFEPIT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IFEPIT_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch11/FITJAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FITJAU_clean_3.2.2_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/RIVDIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/RIVDIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/XICYUF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/XICYUF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/GUJVOX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/GUJVOX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/UDUMIP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/UDUMIP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/UBACUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/UBACUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/UZOBAO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/UZOBAO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/BIRGIU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/BIRGIU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/GAZZIS03_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/GAZZIS03_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/LABMOT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABMOT_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/LABMOT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABMOT_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/REXFEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFEH_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/REXFEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFEH_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/VARWUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VARWUI_clean_3.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/VARWUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VARWUI_clean_3.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/TUZVUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TUZVUH_clean_4.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch41/TUZVUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TUZVUH_clean_4.2.2_298.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/ja6b00695_si_001_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/ja6b00695_si_001_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/DEKPUF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/DEKPUF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/OMOWEU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/OMOWEU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/c5qi00128e_c5qi00128e2_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/c5qi00128e_c5qi00128e2_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/FUSGOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/FUSGOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/YEBLAT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/YEBLAT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/VIZTIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZTIJ_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/VIZTIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZTIJ_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/XISDOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XISDOU_clean_1.3.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/XISDOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XISDOU_clean_1.3.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/FOPTOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FOPTOU_clean_2.1.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch36/FOPTOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FOPTOU_clean_2.1.2_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/QAFDOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/QAFDOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/LABNAG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNAG_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/LABNAG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNAG_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/FUBDIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FUBDIQ_clean_2.1.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/TASWER_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TASWER_clean_2.1.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/FUBDIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FUBDIQ_clean_2.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/TASWER_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TASWER_clean_2.1.2_298.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/LIXXAS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXXAS_clean_3.3.3_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/LIXXAS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXXAS_clean_3.3.3_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/UDAXEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAXEF_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/UDAXEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAXEF_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/VUHNUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNUJ_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/VUHNUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNUJ_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/ERIRIG_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ERIRIG_auto_1.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch42/ERIRIG_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ERIRIG_auto_1.1.1_298.000000_100000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/CUQKOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/CUQKOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/KEJQAR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/KEJQAR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/ic5b00535_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/ic5b00535_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/RUBHUS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/RUBHUS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/NIFZIN_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/NIFZIN_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/FIJFOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/FIJFOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/VOBGAW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOBGAW_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/LIXXEW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXXEW_clean_3.3.3_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/VOBGAW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOBGAW_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/LIXXEW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXXEW_clean_3.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/HOZFIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOZFIN_clean_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/HOZFIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOZFIN_clean_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/IYOCOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IYOCOQ_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/IYOCOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IYOCOQ_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/LUDVAH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVAH_clean_2.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/LUDVAH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVAH_clean_2.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/VOQXIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOQXIK_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/VOQXIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOQXIK_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/QUPDEL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUPDEL_clean_4.4.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/QUPDEL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUPDEL_clean_4.4.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/ZOQTAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQTAC_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/ZOQTAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQTAC_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/VIZSUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZSUU_clean_1.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/VIZSUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZSUU_clean_1.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/LUDVOV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVOV_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/LUDVOV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVOV_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/OGOJOJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OGOJOJ_charged_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/OGOJOJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OGOJOJ_charged_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/ja4050828_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja4050828_auto_1.1.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch27/ja4050828_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja4050828_auto_1.1.2_298.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/ADEGIA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ADEGIA_clean_4.3.3_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/ADEGIA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ADEGIA_clean_4.3.3_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/BIHBAX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BIHBAX_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/UKAQIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UKAQIH_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/UKAQIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UKAQIH_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/LABNUA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNUA_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/LABNUA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNUA_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/RAVDID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAVDID_clean_3.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/RAVDID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAVDID_clean_3.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/INOVEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_INOVEN_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch3/INOVEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_INOVEN_clean_2.2.2_298.000000_100000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/HANKIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/HANKIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/UFEXOT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/WAVQOB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/WAVQOB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/LABJUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABJUV_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/LABJUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABJUV_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/ALULAV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ALULAV_clean_2.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/ALULAV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ALULAV_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/UBULUA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UBULUA_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/UBULUA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UBULUA_clean_2.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/SOHNEJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNEJ_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/SOHNEJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNEJ_clean_2.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/SUKKOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SUKKOZ_clean_3.2.4_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/SUKKOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SUKKOZ_clean_3.2.4_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/REXDIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDIJ_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/REXDIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDIJ_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/VUHMUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHMUI_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/VUHMUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHMUI_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/KOBPUN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KOBPUN_clean_4.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/KOBPUN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KOBPUN_clean_4.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/ULOKOX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKOX_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/ULOKOX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKOX_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/EPUVAN_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EPUVAN_charged_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch30/EPUVAN_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EPUVAN_charged_2.2.2_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/WAPTAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/MEFHUC_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/MEFHUC_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/XULVAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/XULVAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/ja500330a_si_005_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/ja500330a_si_005_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/c6cc02494g_c6cc02494g5_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/c6cc02494g_c6cc02494g5_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/EDADIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/EDADIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/WIYWOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIYWOS_clean_3.1.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/WIYWOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIYWOS_clean_3.1.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/CIWSAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWSAD_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/CIWSAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWSAD_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/ULOLIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLIS_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/ULOLIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLIS_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/VOZVEN01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVEN01_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch22/VOZVEN01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVEN01_clean_1.2.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/AQOMEA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/QUPDEL01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUPDEL01_clean_3.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/IVOLIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IVOLIQ_clean_2.2.3_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/QUPDEL01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUPDEL01_clean_3.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/CIWRUW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWRUW_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/CIWRUW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWRUW_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/ULOJUC01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOJUC01_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/ULOJUC01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOJUC01_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/WIHTAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIHTAK_clean_4.2.4_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/WIHTAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIHTAK_clean_4.2.4_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/EBEXEQ01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXEQ01_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/EBEXEQ01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXEQ01_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/ja512973b_si_003_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_003_auto_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/ja512973b_si_003_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_003_auto_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/XAPTUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPTUE_clean_3.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/XAPTUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPTUE_clean_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/KOJZOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KOJZOZ_clean_1.1.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/KOJZOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KOJZOZ_clean_1.1.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/ZISXOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISXOQ_clean_3.1.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/ZISXOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISXOQ_clean_3.1.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/jacs.5b12516_ja5b12516_si_004_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_004_clean_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch23/jacs.5b12516_ja5b12516_si_004_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_004_clean_2.2.2_298.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/HANKUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/HANKUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/DUZKAM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DUZKAM_clean_1.1.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/DUZKAM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DUZKAM_clean_1.1.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/WODXAQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WODXAQ_clean_3.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/UDAXIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAXIJ_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/UDAXIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAXIJ_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/PEFRUP01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_PEFRUP01_clean_3.1.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch33/PEFRUP01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_PEFRUP01_clean_3.1.2_298.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/HANKOY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/HANKOY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/UCOHUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOHUR_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/UCOHUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOHUR_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/SOHMOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMOS_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/SOHMOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMOS_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/XUNSOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNSOQ_clean_5.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/XUNSOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNSOQ_clean_5.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/CUVHIL01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL01_clean_3.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/CUVHIL01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL01_clean_3.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/ZEZQEC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZEZQEC_clean_3.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/UTOCEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UTOCEN_clean_3.3.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/ZEZQEC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZEZQEC_clean_3.3.3_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch24/UTOCEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UTOCEN_clean_3.3.1_298.000000_100000.data


No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/FALRIV01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/LOFCUF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/LOFCUF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/HUCFAO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/HUCFAO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/LIRFIB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/LIRFIB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/USUBUG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/USUBUG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/FAQGIO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/FAQGIO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/KUZZAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/KUZZAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/HUYKIV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/HUYKIV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/OTOVAW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/OTOVAW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/OTOZEE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/OTOZEE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/BIWYAH10_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/BIWYAH10_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/cm501138g_si_005_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/cm501138g_si_005_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/IGAGUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/IGAGUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/BADJAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/BADJAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/RONCIG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/RONCIG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/SOZPUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/SOZPUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/FALPOY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/FALPOY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/CAHQAG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/CAHQAG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/VEGMOK02_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/VEGMOK02_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/JUVWUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/JUVWUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/WIJXIY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/WIJXIY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/REXFIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFIL_clean_2.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/ja0752540-file002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja0752540-file002_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/REXFIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFIL_clean_2.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/ja0752540-file002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja0752540-file002_clean_2.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/CIWROQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWROQ_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch43/CIWROQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWROQ_clean_2.1.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/LEZXAR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/IWEWAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/IWEWAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/UREVIY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/UREVIY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/AQUDIB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/AQUDIB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/KIRTOW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/KIRTOW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/LAXMIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/LAXMIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/c6dt03852b_c6dt03852b2_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/c6dt03852b_c6dt03852b2_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/HUNBIB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/HUNBIB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/DAKVIW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/DAKVIW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/SINQAH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/SINQAH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/CEHWOD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/CEHWOD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/HOYROE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYROE_clean_3.1.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/HOYROE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYROE_clean_3.1.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/FAVDIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDIS_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/FAVDIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDIS_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/VAKQAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKQAC_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch1/VAKQAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKQAC_clean_1.2.1_298.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/LUWNAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUWNAU_clean_1.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/LUWNAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUWNAU_clean_1.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/WIKXUJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIKXUJ_charged_2.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/WIKXUJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIKXUJ_charged_2.2.2_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/CAKFEB01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAKFEB01_clean_2.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/QISNIR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QISNIR_clean_2.2.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/CAKFEB01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAKFEB01_clean_2.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/QISNIR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QISNIR_clean_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/IWEVUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEVUD_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/IWEVUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEVUD_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/IPEBAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IPEBAI_clean_2.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/IPEBAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IPEBAI_clean_2.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/RIYBAE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBAE_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch16/RIYBAE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBAE_clean_1.2.1_298.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/KUYPIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/KUYPIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/LAWGOG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/LAWGOG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/BIFGOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_BIFGOO_clean_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/CIWREG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWREG_clean_2.1.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/CIWREG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWREG_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/SACDOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SACDOR_clean_2.1.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/BIFGOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BIFGOO_clean_2.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/SACDOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SACDOR_clean_2.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/IWEWIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEWIS_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/IWEWIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEWIS_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/WUDZAY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZAY_clean_1.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/WUDZAY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZAY_clean_1.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/ODEKAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ODEKAL_clean_4.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/ODEKAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ODEKAL_clean_4.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/ja5b02777_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja5b02777_si_003_clean_3.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/ja5b02777_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja5b02777_si_003_clean_3.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/MUBZUG_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MUBZUG_auto_2.2.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/MUBZUG_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MUBZUG_auto_2.2.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/UDAWOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAWOO_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch5/UDAWOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAWOO_clean_1.2.1_298.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/HANKEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/HANKEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/ULOLAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLAK_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/ULOLAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLAK_clean_1.2.1_298.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/ULOKUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKUD_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/ULOKUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKUD_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/MUBZOA_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MUBZOA_auto_2.2.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/MUBZOA_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MUBZOA_auto_2.2.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/XUNGUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNGUJ_clean_5.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/XUNGUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNGUJ_clean_5.3.2_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/UMEDOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UMEDOH_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/UMEDOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UMEDOH_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/COKJIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_COKJIX_clean_4.3.2_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/COKJIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_COKJIX_clean_4.3.2_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/ja5b02777_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja5b02777_si_002_clean_3.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch17/ja5b02777_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja5b02777_si_002_clean_3.3.3_298.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/CURBOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CURBOH_clean_2.2.1_298.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/CURBOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CURBOH_clean_2.2.1_298.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/QAWRIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QAWRIQ_clean_3.3.3_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/QAWRIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QAWRIQ_clean_3.3.3_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/ULOKAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKAJ_clean_1.2.1_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/TAMZUE_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TAMZUE_charged_3.3.2_298.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/ULOKAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKAJ_clean_1.2.1_298.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/TAMZUE_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TAMZUE_charged_3.3.2_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/VUHNAP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNAP_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/VUHNAP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNAP_clean_1.2.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/XOFGEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XOFGEG_clean_1.1.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/XOFGEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XOFGEG_clean_1.1.1_298.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/CIWRIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWRIK_clean_1.2.1_298.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch0/CIWRIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWRIK_clean_1.2.1_298.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/HEBTEP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/HEBTEP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/OPOCUS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/OPOCUS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TUDQOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TUDQOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/LEZMIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/LEZMIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/REBRUM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/REBRUM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/KUJNEJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/KUJNEJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/LAGNEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/LAGNEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/SOZSUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/SOZSUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/PELRAB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/PELRAB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/ATEYUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/ATEYUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/NARHEV_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/NARHEV_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/KUTKUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/KUTKUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XAQTEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XAQTEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/PENNIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/PENNIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/MAMVED_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/MAMVED_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/EYIYES_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/EYIYES_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/IXISUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/IXISUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/VUQLEZ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/VUQLEZ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XAKLIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XAKLIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/NEYVEU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/NEYVEU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/SITTUM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/SITTUM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/MICNUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/MICNUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/COKPEZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/COKPEZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/UJIPAG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/UJIPAG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/FALDAA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/FALDAA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/OPIPUZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/OPIPUZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/BIHBEB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/BIHBEB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/CEKROB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/CEKROB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/OGIBUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/OGIBUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TURDUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TURDUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XISPEW01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XISPEW01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/nchem.2258-s3_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/nchem.2258-s3_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/ZAXQOG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/ZAXQOG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XISPUM01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XISPUM01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/KEVPEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/KEVPEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/PUMGIP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/PUMGIP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/QAHDUA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/QAHDUA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/acs.inorgchem.6b00433_ic6b00433_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/acs.inorgchem.6b00433_ic6b00433_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/SUNHOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/SUNHOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XIQHIO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XIQHIO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/IJUJEE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/IJUJEE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/cg801267m_si_004_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/cg801267m_si_004_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/UNECUN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/UNECUN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XAMDOF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/XAMDOF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/ECALOL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/ECALOL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/AWUPOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/AWUPOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/WEGGAS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/WEGGAS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/BAWRUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/BAWRUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/ISIYUF05_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/ISIYUF05_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/VUGYIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/VUGYIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/LAGWUN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/LAGWUN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TASZAQ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TASZAQ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/acscombsci.5b00188_5024922_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/acscombsci.5b00188_5024922_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/YORSOP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/YORSOP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TUJGIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TUJGIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/HABZEQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/HABZEQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TANMIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/TANMIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/OWILAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/OWILAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/NIWZIE18_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/NIWZIE18_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/UCUTIW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/UCUTIW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/HAWZEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/HAWZEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/VEYREY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/VEYREY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/PIBNUK01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/PIBNUK01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/HIWLUW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc298.0K/mc_data/batch9/HIWLUW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch25/LUDVIP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVIP_clean_2.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch25/FAVDAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDAK_clean_1.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch25/LUDVIP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVIP_clean_2.2.1_323.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch25/FAVDAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDAK_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch25/VUPDOB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUPDOB_clean_4.1.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch25/KACGED_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KACGED_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch25/KACGED_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KACGED_clean_1.2.1_323.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/RAHNUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/RAHNUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/XAFNOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAFNOH_clean_4.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/XAFNOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAFNOH_clean_4.3.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/SOHNIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNIN_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/SOHNIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNIN_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/HUZFIS_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HUZFIS_charged_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/ULOKEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKEN_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/ULOKEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKEN_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/LABPUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPUC_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/LABPUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPUC_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/IMISIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IMISIH_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch38/IMISIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IMISIH_clean_2.2.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/SOHNAF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNAF_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/SOHNAF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNAF_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/ZOQTIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQTIK_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/ZOQTIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQTIK_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/IPEBEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IPEBEM_clean_1.1.4_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/IPEBEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IPEBEM_clean_1.1.4_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/GUVKUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUVKUE_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/GUVKUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUVKUE_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/ECALIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ECALIF_clean_4.1.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch19/ECALIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ECALIF_clean_4.1.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/LIQJEC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIQJEC_clean_2.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/LIQJEC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIQJEC_clean_2.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/ULOMAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOMAL_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/ULOMAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOMAL_clean_1.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/ic403134c_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ic403134c_si_002_clean_5.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/ic403134c_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ic403134c_si_002_clean_5.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/LUDVUB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVUB_clean_1.1.4_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/LUDVUB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVUB_clean_1.1.4_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/REXDOP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDOP_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/REXDOP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDOP_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/OQUFAJ01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OQUFAJ01_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/REXCOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCOO_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/REXCOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCOO_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/VIWZOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIWZOR_clean_3.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch45/VIWZOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIWZOR_clean_3.2.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/REXDEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDEF_clean_2.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/MIVPAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MIVPAJ_clean_4.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/MIVPAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MIVPAJ_clean_4.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/REXDEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDEF_clean_2.2.1_323.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/IHILUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IHILUI_clean_4.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/IHILUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IHILUI_clean_4.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/XIPBOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIPBOO_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/UZUXOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UZUXOE_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/XIPBOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIPBOO_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/UZUXOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UZUXOE_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/WUDZOM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZOM_clean_1.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/WUDZOM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZOM_clean_1.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/IRAYOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IRAYOQ_clean_2.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/XUNGOD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNGOD_clean_5.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch35/XUNGOD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNGOD_clean_5.3.2_323.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/ZAZNUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/ZAZNUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/SOHMUY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMUY_clean_2.1.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/LABPOW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPOW_clean_2.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/SOHMUY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMUY_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/LABPOW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPOW_clean_2.2.1_323.000000_10000.data



Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/YAHWAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_YAHWAI_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/YAHWAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_YAHWAI_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/XEVHEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XEVHEN_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/XEVHEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XEVHEN_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/POBNEA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POBNEA_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/POBNEA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POBNEA_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/UZUTUG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UZUTUG_clean_1.2.1_323.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/UZUTUG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UZUTUG_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/LABNIO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNIO_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch2/LABNIO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNIO_clean_1.2.1_323.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/XIJJEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/XIJJEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/IBIYOI_ion_b/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IBIYOI_ion_b_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/IBIYOI_ion_b/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IBIYOI_ion_b_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/EBEXEQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXEQ_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/EBEXEQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXEQ_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/UCOJAZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJAZ_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/UCOJAZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJAZ_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/jacs.5b12516_ja5b12516_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_003_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/jacs.5b12516_ja5b12516_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_003_clean_2.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/acs.inorgchem.6b02407_ic6b02407_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_002_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/acs.inorgchem.6b02407_ic6b02407_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_002_clean_3.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/LIXMIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXMIQ_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch32/LIXMIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXMIQ_clean_3.2.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch8/QUSBEM_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUSBEM_charged_5.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch8/QUSBEM_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUSBEM_charged_5.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch8/ORAGEU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ORAGEU_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch8/ORAGEU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ORAGEU_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch8/ULOKUD01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKUD01_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch8/ULOKUD01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKUD01_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch8/FAVDEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDEO_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch8/FAVDEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDEO_clean_1.2.1_323.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/ULOLUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLUE_clean_1.1.4_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/ULOLUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLUE_clean_1.1.4_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/ic5b00096_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ic5b00096_auto_1.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/ic5b00096_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ic5b00096_auto_1.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/COQJID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_COQJID_clean_3.1.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/COQJID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_COQJID_clean_3.1.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/JALTUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JALTUL_clean_2.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/JALTUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JALTUL_clean_2.3.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/ZITRUP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZITRUP_clean_3.3.3_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/ZITRUP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZITRUP_clean_3.3.3_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/XIGHEB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIGHEB_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch34/XIGHEB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIGHEB_clean_1.2.1_323.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/SACDUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SACDUX_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/SACDUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SACDUX_clean_2.1.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/IYOCIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IYOCIK_clean_1.2.1_323.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/HAPBEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HAPBEI_clean_3.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/IYOCIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IYOCIK_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/HAPBEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HAPBEI_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/LEYYET_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LEYYET_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/TURBUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TURBUE_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/TURBUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TURBUE_clean_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/VUHMOC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHMOC_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch15/VUHMOC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHMOC_clean_1.2.1_323.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch4/RUBLEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch4/RUBLEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch4/cg501730q_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_cg501730q_si_002_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch4/cg501730q_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_cg501730q_si_002_clean_2.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch4/HOYREU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYREU_clean_2.2.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch4/HOYREU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYREU_clean_2.2.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch4/ja512311a_si_003_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512311a_si_003_auto_1.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch4/ja512311a_si_003_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512311a_si_003_auto_1.1.1_323.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/ZUCKIT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/ZUCKIT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/CIXBUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIXBUH_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/CIXBUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIXBUH_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/ENAFOP_ion_b/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ENAFOP_ion_b_2.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/ENAFOP_ion_b/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ENAFOP_ion_b_2.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/XAPDAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPDAU_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/XAPDAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPDAU_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/GUVLAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUVLAL_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/GUVLAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUVLAL_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/OVADAR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OVADAR_clean_4.4.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/OVADAR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OVADAR_clean_4.4.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/SOXHUI_SL/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOXHUI_SL_2.2.5_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/SOXHUI_SL/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOXHUI_SL_2.2.5_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/PORLEP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_PORLEP_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/PORLEP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_PORLEP_clean_2.1.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/FUBDEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FUBDEM_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch18/FUBDEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FUBDEM_clean_2.1.1_323.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/NIVWIY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NIVWIY_clean_6.4.4_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/ISUGIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ISUGIN_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/ISUGIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ISUGIN_clean_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/NIVWIY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NIVWIY_clean_6.4.4_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/YEZSEC01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_YEZSEC01_clean_1.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/YEZSEC01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_YEZSEC01_clean_1.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/VAKPUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKPUV_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/VAKPUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKPUV_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/ICITUK_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ICITUK_charged_2.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/ICITUK_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ICITUK_charged_2.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/LUDVEL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVEL_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/LUDVEL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVEL_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/WEFZIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WEFZIS_clean_4.4.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch39/WEFZIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WEFZIS_clean_4.4.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/SEHMUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SEHMUO_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/UDAWUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAWUU_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/SEHMUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SEHMUO_clean_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/UDAWUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAWUU_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/HAPBAE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HAPBAE_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/HAPBAE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HAPBAE_clean_3.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/TISWEZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TISWEZ_clean_3.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/TISWEZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TISWEZ_clean_3.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/ZEZPIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZEZPIF_clean_2.3.3_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/ZEZPIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZEZPIF_clean_2.3.3_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/FANDEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FANDEG_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/FANDEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FANDEG_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/GOYXID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GOYXID_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch13/GOYXID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GOYXID_clean_3.3.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/WODWUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WODWUJ_clean_3.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/RIYBEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBEI_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/GARTAX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GARTAX_clean_3.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/WODWUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WODWUJ_clean_3.3.3_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/RIYBEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBEI_clean_2.1.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/GARTAX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GARTAX_clean_3.3.3_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/POKVAO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POKVAO_clean_5.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/POKVAO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POKVAO_clean_5.3.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/VOZVIR01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVIR01_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/VOZVIR01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVIR01_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/HABCEV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HABCEV_clean_1.1.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/HABCEV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HABCEV_clean_1.1.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/RIYBIM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBIM_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/RIYBIM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBIM_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/QESYOD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QESYOD_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/QESYOD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QESYOD_clean_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/VUHPUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHPUL_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/VUHPUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHPUL_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/ULOLEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLEO_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch20/ULOLEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLEO_clean_1.2.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/XOMJOY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XOMJOY_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/XOMJOY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XOMJOY_clean_3.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/WUDZUS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZUS_clean_1.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/WUDZUS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZUS_clean_1.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/XUNHAQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNHAQ_clean_5.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/XUNHAQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNHAQ_clean_5.3.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/XIGHAX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIGHAX_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/XIGHAX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIGHAX_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/CUVHIL02_clean_h/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL02_clean_h_3.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/CUVHIL02_clean_h/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL02_clean_h_3.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/LABPEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPEM_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch26/LABPEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPEM_clean_1.2.1_323.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/IMUKUW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/IMUKUW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/AMUWIP_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AMUWIP_charged_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/AMUWIP_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AMUWIP_charged_2.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/AGABIU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AGABIU_clean_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/LIKCOY_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIKCOY_charged_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/ja512973b_si_002_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_002_auto_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/LIKCOY_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIKCOY_charged_2.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/AGABIU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AGABIU_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/ja512973b_si_002_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_002_auto_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/ZIHTEP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZIHTEP_clean_4.3.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/ZIHTEP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZIHTEP_clean_4.3.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/LABNOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNOU_clean_1.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/LABNOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNOU_clean_1.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/WUDYUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDYUR_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/WUDYUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDYUR_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/CIXCAO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIXCAO_clean_2.1.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/CIXCAO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIXCAO_clean_2.1.1_323.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/LABQAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABQAJ_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch21/LABQAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABQAJ_clean_1.2.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/UCOJED_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJED_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/NIFZOT_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NIFZOT_charged_2.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/NIFZOT_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NIFZOT_charged_2.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/UCOJED_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJED_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/NARPAA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NARPAA_clean_3.2.3_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/NARPAA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NARPAA_clean_3.2.3_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/UVUQOT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UVUQOT_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/NEGMUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NEGMUI_clean_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/NEGMUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NEGMUI_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/UVUQOT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UVUQOT_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/CAYMIZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAYMIZ_clean_4.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/CAYMIZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAYMIZ_clean_4.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/HOYRIY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYRIY_clean_2.2.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch6/HOYRIY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYRIY_clean_2.2.3_323.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/RIVDEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/RIVDEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/ja512973b_si_004_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_004_auto_1.1.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/KACGAZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KACGAZ_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/ja512973b_si_004_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_004_auto_1.1.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/KACGAZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KACGAZ_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/REXCEE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCEE_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/REXCEE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCEE_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/GEVXIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GEVXIQ_clean_3.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/GEVXIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GEVXIQ_clean_3.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/WUDZIG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZIG_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch29/WUDZIG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZIG_clean_1.2.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/DAMDUT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DAMDUT_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/LUDTUZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDTUZ_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/LUDTUZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDTUZ_clean_1.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/DAMDUT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DAMDUT_clean_1.2.1_323.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/VAKPOP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKPOP_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/LABNEK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNEK_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/CAKFEB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAKFEB_clean_3.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/CAKFEB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAKFEB_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/VAKPOP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKPOP_clean_1.2.1_323.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/LABNEK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNEK_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/UCOJIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJIH_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/UCOJIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJIH_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/ASEJOZ01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ASEJOZ01_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/VUHPOF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHPOF_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch40/VUHPOF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHPOF_clean_1.2.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/RAKDEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAKDEN_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/RAKDAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAKDAJ_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/RAKDAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAKDAJ_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/BUPFEY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BUPFEY_clean_1.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/BUPFEY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_BUPFEY_clean_1.1.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/SOMCON_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOMCON_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/RAKDEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAKDEN_clean_1.2.1_323.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/SOMCON_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOMCON_clean_2.1.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/LABMUZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABMUZ_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/LABMUZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABMUZ_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/JEDJUY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JEDJUY_clean_4.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/JEDJUY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JEDJUY_clean_4.3.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/CIPLIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIPLIX_clean_2.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/CIPLIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIPLIX_clean_2.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/VIZSOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZSOO_clean_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/VIZSOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZSOO_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/REXCUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCUU_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/REXCUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCUU_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/QOGGID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOGGID_clean_4.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch7/QOGGID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOGGID_clean_4.2.2_323.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/OCUNAC_manual/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/OCUNAC_manual/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/REXFOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFOR_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/REXFOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFOR_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/CAWBUY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAWBUY_clean_4.4.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/POFGUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POFGUO_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/POFGUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POFGUO_clean_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/RUBTAK03_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RUBTAK03_auto_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/RUBTAK03_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RUBTAK03_auto_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/UTOCAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UTOCAJ_clean_3.3.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/UTOCAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UTOCAJ_clean_3.3.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/CEDFIC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CEDFIC_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/CEDFIC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CEDFIC_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/DOGMET_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DOGMET_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/DOGMET_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DOGMET_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/QETCUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QETCUO_clean_3.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/QETCUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QETCUO_clean_3.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/SOHMEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMEI_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch37/SOHMEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMEI_clean_2.1.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/REXDAB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDAB_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/EBEXIU02_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXIU02_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/GEGBOL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GEGBOL_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/GEGBOL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GEGBOL_clean_2.1.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/EBEXIU02_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXIU02_clean_3.3.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/REXDAB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDAB_clean_2.1.1_323.000000_10000.data



Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/FOFMOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FOFMOE_clean_3.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/OSIKIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OSIKIL_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/OSIKIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OSIKIL_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/FOFMOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FOFMOE_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/DEFRIR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DEFRIR_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/RIYBOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBOS_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/DEFRIR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DEFRIR_clean_3.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/RIYBOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBOS_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/ja512311a_si_007_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512311a_si_007_auto_1.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch14/ja512311a_si_007_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512311a_si_007_auto_1.1.1_323.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/LAFRAN01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/LAFRAN01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/XEGKUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XEGKUR_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/XEGKUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XEGKUR_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/ULOJUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOJUC_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/ULOJUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOJUC_clean_1.2.1_323.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/JOVROD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JOVROD_clean_3.3.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/jacs.5b12516_ja5b12516_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_002_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/jacs.5b12516_ja5b12516_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_002_clean_2.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/JOVROD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JOVROD_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/RIHXIR_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIHXIR_charged_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch44/RIHXIR_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIHXIR_charged_2.2.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/XAPDEY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPDEY_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/REXFUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFUX_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/XAPDEY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPDEY_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/ZISXEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISXEG_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/HUCBAJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HUCBAJ_charged_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/HUCBAJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HUCBAJ_charged_3.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/ZISXEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISXEG_clean_2.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/REXFUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFUX_clean_2.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/REXCII_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCII_clean_2.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/REXCII_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCII_clean_2.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/acs.inorgchem.6b02407_ic6b02407_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_003_clean_2.2.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/acs.inorgchem.6b02407_ic6b02407_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_003_clean_2.2.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/CUVHIL_clean_h/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL_clean_h_3.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/CUVHIL_clean_h/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL_clean_h_3.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/ja507947d_si_001_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja507947d_si_001_auto_1.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/ja507947d_si_001_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja507947d_si_001_auto_1.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/GUSCIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUSCIH_clean_3.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch31/GUSCIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUSCIH_clean_3.3.3_323.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/VUJBOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/VUJBOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/QARLON_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QARLON_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/QARLON_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QARLON_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/LAKFIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LAKFIN_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/SARMII_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SARMII_clean_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/VUHNIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNIX_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/MEXJAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MEXJAC_clean_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/SARMII_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SARMII_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/MEXJAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MEXJAC_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/LAKFIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LAKFIN_clean_2.1.1_323.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/VUHNIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNIX_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/SUXGUP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SUXGUP_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/QOJTUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOJTUE_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/QOJTUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOJTUE_clean_2.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/SUXGUP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SUXGUP_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/VOZVAJ01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVAJ01_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/VOZVAJ01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVAJ01_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/ZOQSUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQSUV_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/ZOQSUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQSUV_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/VUHPAR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHPAR_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/VUHPAR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHPAR_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/LABQEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABQEN_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch12/LABQEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABQEN_clean_1.2.1_323.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/XITYEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/XITYEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/OJOZOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OJOZOE_clean_5.4.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/OJOZOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OJOZOE_clean_5.4.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/TEJGEW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TEJGEW_clean_3.3.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/TEJGEW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TEJGEW_clean_3.3.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/DOMGAP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DOMGAP_clean_1.1.3_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/DOMGAP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DOMGAP_clean_1.1.3_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/QARMAA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QARMAA_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/QARMAA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QARMAA_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/AKUHOD01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AKUHOD01_clean_4.3.3_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch10/AKUHOD01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AKUHOD01_clean_4.3.3_323.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/OKUJUB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/OKUJUB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/QOJVAM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOJVAM_clean_3.3.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/QOJVAM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOJVAM_clean_3.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/ZISYAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISYAD_clean_4.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/acs.cgd.5b01554_VAGNUP1452791_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_acs.cgd.5b01554_VAGNUP1452791_clean_2.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/ZISYAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISYAD_clean_4.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/LOCNIB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LOCNIB_clean_3.3.3_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/LOCNIB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LOCNIB_clean_3.3.3_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/QUKYUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUKYUR_clean_4.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/ja500330a_si_009_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja500330a_si_009_auto_1.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/ja500330a_si_009_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja500330a_si_009_auto_1.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/IFEPIT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IFEPIT_clean_3.3.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/IFEPIT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IFEPIT_clean_3.3.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/FITJAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FITJAU_clean_3.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch11/FITJAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FITJAU_clean_3.2.2_323.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/RIVDIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/RIVDIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/XICYUF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/XICYUF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/LABMOT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABMOT_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/LABMOT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABMOT_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/REXFEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFEH_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/REXFEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFEH_clean_2.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/VARWUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VARWUI_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/VARWUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VARWUI_clean_3.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/TUZVUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TUZVUH_clean_4.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch41/TUZVUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TUZVUH_clean_4.2.2_323.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch36/ja6b00695_si_001_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch36/ja6b00695_si_001_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch36/VIZTIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZTIJ_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch36/VIZTIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZTIJ_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch36/XISDOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XISDOU_clean_1.3.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch36/FOPTOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FOPTOU_clean_2.1.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch36/FOPTOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FOPTOU_clean_2.1.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch36/XISDOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XISDOU_clean_1.3.1_323.000000_100000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/QAFDOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/QAFDOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/LABNAG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNAG_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/TASWER_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TASWER_clean_2.1.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/TASWER_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TASWER_clean_2.1.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/LABNAG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNAG_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/FUBDIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FUBDIQ_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/FUBDIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FUBDIQ_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/LIXXAS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXXAS_clean_3.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/LIXXAS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXXAS_clean_3.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/UDAXEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAXEF_clean_1.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/NICJUG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NICJUG_clean_3.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/UDAXEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAXEF_clean_1.2.1_323.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/VUHNUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNUJ_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/VUHNUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNUJ_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/ERIRIG_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ERIRIG_auto_1.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch42/ERIRIG_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ERIRIG_auto_1.1.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/VOBGAW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOBGAW_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/LIXXEW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXXEW_clean_3.3.3_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/LIXXEW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXXEW_clean_3.3.3_323.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/VOBGAW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOBGAW_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/HOZFIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOZFIN_clean_2.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/HOZFIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOZFIN_clean_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/IYOCOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IYOCOQ_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/IYOCOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IYOCOQ_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/LUDVAH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVAH_clean_2.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/LUDVAH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVAH_clean_2.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/VOQXIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOQXIK_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/VOQXIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOQXIK_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/QUPDEL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUPDEL_clean_4.4.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/QUPDEL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUPDEL_clean_4.4.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/ZOQTAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQTAC_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/ZOQTAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQTAC_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/VIZSUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZSUU_clean_1.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/VIZSUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZSUU_clean_1.1.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/LUDVOV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVOV_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/LUDVOV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVOV_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/OGOJOJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OGOJOJ_charged_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/OGOJOJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OGOJOJ_charged_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/ja4050828_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja4050828_auto_1.1.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch27/ja4050828_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja4050828_auto_1.1.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/ADEGIA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ADEGIA_clean_4.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/ADEGIA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ADEGIA_clean_4.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/UKAQIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UKAQIH_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/UKAQIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UKAQIH_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/LABNUA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNUA_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/LABNUA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNUA_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/RAVDID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAVDID_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/RAVDID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAVDID_clean_3.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/INOVEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_INOVEN_clean_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch3/INOVEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_INOVEN_clean_2.2.2_323.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/HANKIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/HANKIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/LABJUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABJUV_clean_3.3.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/ALULAV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ALULAV_clean_2.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/UBULUA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UBULUA_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/LABJUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABJUV_clean_3.3.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/UBULUA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UBULUA_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/ALULAV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ALULAV_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/SOHNEJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNEJ_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/SUKKOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SUKKOZ_clean_3.2.4_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/SUKKOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SUKKOZ_clean_3.2.4_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/REXDIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDIJ_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/REXDIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDIJ_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/SOHNEJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNEJ_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/VUHMUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHMUI_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/VUHMUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHMUI_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/KOBPUN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KOBPUN_clean_4.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/KOBPUN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KOBPUN_clean_4.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/ULOKOX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKOX_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/ULOKOX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKOX_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/EPUVAN_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EPUVAN_charged_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch30/EPUVAN_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EPUVAN_charged_2.2.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/WIYWOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIYWOS_clean_3.1.3_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/WIYWOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIYWOS_clean_3.1.3_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/CIWSAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWSAD_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/CIWSAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWSAD_clean_2.1.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/MOMSIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MOMSIS_clean_2.1.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/ULOLIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLIS_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/ULOLIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLIS_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/VOZVEN01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVEN01_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/VOZVEN01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVEN01_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/XULVAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XULVAD_clean_4.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch22/XULVAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XULVAD_clean_4.3.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/QUPDEL01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUPDEL01_clean_3.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/QUPDEL01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUPDEL01_clean_3.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/CIWRUW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWRUW_clean_2.1.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/CIWRUW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWRUW_clean_2.1.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/ULOJUC01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOJUC01_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/ULOJUC01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOJUC01_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/WIHTAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIHTAK_clean_4.2.4_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/WIHTAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIHTAK_clean_4.2.4_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/EBEXEQ01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXEQ01_clean_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/EBEXEQ01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXEQ01_clean_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/ja512973b_si_003_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_003_auto_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/ja512973b_si_003_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_003_auto_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/XAPTUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPTUE_clean_3.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/XAPTUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPTUE_clean_3.3.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/KOJZOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KOJZOZ_clean_1.1.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/KOJZOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KOJZOZ_clean_1.1.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/ZISXOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISXOQ_clean_3.1.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/ZISXOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISXOQ_clean_3.1.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/jacs.5b12516_ja5b12516_si_004_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_004_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch23/jacs.5b12516_ja5b12516_si_004_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_004_clean_2.2.2_323.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch33/HANKUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch33/HANKUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch33/DUZKAM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DUZKAM_clean_1.1.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch33/DUZKAM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DUZKAM_clean_1.1.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch33/UDAXIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAXIJ_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch33/UDAXIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAXIJ_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch33/PEFRUP01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_PEFRUP01_clean_3.1.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch33/PEFRUP01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_PEFRUP01_clean_3.1.2_323.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/HANKOY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/HANKOY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/UCOHUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOHUR_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/UCOHUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOHUR_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/SOHMOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMOS_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/SOHMOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMOS_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/XUNSOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNSOQ_clean_5.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/XUNSOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNSOQ_clean_5.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/CUVHIL01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL01_clean_3.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/CUVHIL01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL01_clean_3.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/ZEZQEC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZEZQEC_clean_3.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/UTOCEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UTOCEN_clean_3.3.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/UTOCEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UTOCEN_clean_3.3.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch24/ZEZQEC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZEZQEC_clean_3.3.3_323.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch43/ja0752540-file002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja0752540-file002_clean_2.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch43/ja0752540-file002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja0752540-file002_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch43/REXFIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFIL_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch43/REXFIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFIL_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch43/CIWROQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWROQ_clean_2.1.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch43/CIWROQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWROQ_clean_2.1.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch43/RONCIG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RONCIG_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch43/RONCIG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RONCIG_clean_2.2.2_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch1/HOYROE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYROE_clean_3.1.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch1/HOYROE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYROE_clean_3.1.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch1/FAVDIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDIS_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch1/FAVDIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDIS_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch1/VAKQAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKQAC_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch1/VAKQAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKQAC_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch1/IWEWAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEWAK_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch1/IWEWAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEWAK_clean_1.2.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/LUWNAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUWNAU_clean_1.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/LUWNAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUWNAU_clean_1.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/WIKXUJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIKXUJ_charged_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/WIKXUJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIKXUJ_charged_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/CAKFEB01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAKFEB01_clean_2.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/CAKFEB01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAKFEB01_clean_2.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/QISNIR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QISNIR_clean_2.2.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/QISNIR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QISNIR_clean_2.2.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/IWEVUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEVUD_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/IWEVUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEVUD_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/IPEBAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IPEBAI_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/IPEBAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IPEBAI_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/RIYBAE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBAE_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch16/RIYBAE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBAE_clean_1.2.1_323.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/SACDOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SACDOR_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/SACDOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SACDOR_clean_2.1.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/BIFGOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_BIFGOO_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/CIWREG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWREG_clean_2.1.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/CIWREG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWREG_clean_2.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/BIFGOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BIFGOO_clean_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/IWEWIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEWIS_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/IWEWIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEWIS_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/WUDZAY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZAY_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/WUDZAY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZAY_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/ODEKAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ODEKAL_clean_4.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/ODEKAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ODEKAL_clean_4.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/ja5b02777_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja5b02777_si_003_clean_3.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/ja5b02777_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja5b02777_si_003_clean_3.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/MUBZUG_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MUBZUG_auto_2.2.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/MUBZUG_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MUBZUG_auto_2.2.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/UDAWOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAWOO_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch5/UDAWOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAWOO_clean_1.2.1_323.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/HANKEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/HANKEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/ULOLAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLAK_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/ULOLAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLAK_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/ULOKUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKUD_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/ULOKUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKUD_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/MUBZOA_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MUBZOA_auto_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/MUBZOA_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MUBZOA_auto_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/XUNGUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNGUJ_clean_5.3.2_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/XUNGUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNGUJ_clean_5.3.2_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/UMEDOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UMEDOH_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/UMEDOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UMEDOH_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/COKJIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_COKJIX_clean_4.3.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/COKJIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_COKJIX_clean_4.3.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/ja5b02777_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja5b02777_si_002_clean_3.3.3_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch17/ja5b02777_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja5b02777_si_002_clean_3.3.3_323.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/CURBOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CURBOH_clean_2.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/CURBOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CURBOH_clean_2.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/QAWRIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QAWRIQ_clean_3.3.3_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/QAWRIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QAWRIQ_clean_3.3.3_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/ECIYEU01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ECIYEU01_clean_2.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/ULOKAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKAJ_clean_1.2.1_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/TAMZUE_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TAMZUE_charged_3.3.2_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/ULOKAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKAJ_clean_1.2.1_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/TAMZUE_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TAMZUE_charged_3.3.2_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/VUHNAP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNAP_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/VUHNAP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNAP_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/XOFGEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XOFGEG_clean_1.1.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/XOFGEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XOFGEG_clean_1.1.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/CIWRIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWRIK_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch0/CIWRIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWRIK_clean_1.2.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch9/IXISUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IXISUD_clean_2.2.2_323.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch9/IXISUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IXISUD_clean_2.2.2_323.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch9/RAKCUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAKCUC_clean_1.2.1_323.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch9/RAKCUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAKCUC_clean_1.2.1_323.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch9/SOHMIM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMIM_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch9/SOHMIM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMIM_clean_1.2.1_323.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch9/FUBDAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FUBDAI_clean_1.2.1_323.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc323.0K/mc_data/batch9/FUBDAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FUBDAI_clean_1.2.1_323.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

number of isotherm data points:  17112
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/IWEWEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEWEO_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/LULXOG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LULXOG_clean_3.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/IWEWEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEWEO_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/LULXOG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LULXOG_clean_3.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/ja500330a_si_006_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja500330a_si_006_auto_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/ja500330a_si_006_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja500330a_si_006_auto_1.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/XIGHIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIGHIF_clean_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/XIGHIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIGHIF_clean_2.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/LABPIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPIQ_clean_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/LABPIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPIQ_clean_2.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/BEPWEA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BEPWEA_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/BEPWEA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_BEPWEA_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/XEVGUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XEVGUC_clean_1.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/XEVGUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XEVGUC_clean_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/REXDUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDUV_clean_2.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch28/REXDUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDUV_clean_2.2.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch25/LUDVIP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVIP_clean_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch25/FAVDAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDAK_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch25/LUDVIP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVIP_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch25/FAVDAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDAK_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch25/KACGED_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KACGED_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch25/KACGED_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KACGED_clean_1.2.1_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/RAHNUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/RAHNUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/XAFNOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAFNOH_clean_4.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/XAFNOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAFNOH_clean_4.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/SOHNIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNIN_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/SOHNIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNIN_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/ULOKEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKEN_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/ULOKEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKEN_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/LABPUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPUC_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/LABPUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPUC_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/IMISIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IMISIH_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch38/IMISIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IMISIH_clean_2.2.2_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/SOHNAF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNAF_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/SOHNAF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNAF_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/ZOQTIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQTIK_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/ZOQTIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQTIK_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/IPEBEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IPEBEM_clean_1.1.4_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/IPEBEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IPEBEM_clean_1.1.4_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/GUVKUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUVKUE_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/GUVKUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUVKUE_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/ECALIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ECALIF_clean_4.1.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch19/ECALIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ECALIF_clean_4.1.2_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/LIQJEC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIQJEC_clean_2.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/ULOMAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOMAL_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/ULOMAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOMAL_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/LIQJEC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIQJEC_clean_2.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/ORAQUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ORAQUU_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/ic403134c_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ic403134c_si_002_clean_5.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/ic403134c_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ic403134c_si_002_clean_5.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/LUDVUB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVUB_clean_1.1.4_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/LUDVUB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVUB_clean_1.1.4_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/REXDOP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDOP_clean_2.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/REXDOP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDOP_clean_2.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/REXCOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCOO_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/REXCOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCOO_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/VIWZOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIWZOR_clean_3.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch45/VIWZOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIWZOR_clean_3.2.2_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/REXDEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDEF_clean_2.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/REXDEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDEF_clean_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/MIVPAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MIVPAJ_clean_4.3.2_473.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/MIVPAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MIVPAJ_clean_4.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/IHILUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IHILUI_clean_4.3.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/IHILUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IHILUI_clean_4.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/XIPBOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIPBOO_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/UZUXOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UZUXOE_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/UZUXOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UZUXOE_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/XIPBOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIPBOO_clean_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/WUDZOM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZOM_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/WUDZOM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZOM_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/XUNGOD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNGOD_clean_5.3.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch35/XUNGOD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNGOD_clean_5.3.2_473.000000_100000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/ZAZNUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/ZAZNUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/LABPOW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPOW_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/SOHMUY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMUY_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/SOHMUY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMUY_clean_2.1.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/LABPOW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPOW_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/YAHWAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_YAHWAI_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/YAHWAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_YAHWAI_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/XEVHEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XEVHEN_clean_3.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/XEVHEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XEVHEN_clean_3.3.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/CODGAE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CODGAE_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/MOVGUB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MOVGUB_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/POBNEA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POBNEA_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/POBNEA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POBNEA_clean_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/UZUTUG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UZUTUG_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/UZUTUG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UZUTUG_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/LABNIO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNIO_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch2/LABNIO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNIO_clean_1.2.1_473.000000_100000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/XIJJEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/XIJJEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/IBIYOI_ion_b/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IBIYOI_ion_b_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/IBIYOI_ion_b/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IBIYOI_ion_b_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/EBEXEQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXEQ_clean_3.3.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/EBEXEQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXEQ_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/UCOJAZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJAZ_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/UCOJAZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJAZ_clean_2.1.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/jacs.5b12516_ja5b12516_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_003_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/jacs.5b12516_ja5b12516_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_003_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/acs.inorgchem.6b02407_ic6b02407_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_002_clean_3.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/LIXMIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXMIQ_clean_3.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/acs.inorgchem.6b02407_ic6b02407_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_002_clean_3.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch32/LIXMIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXMIQ_clean_3.2.2_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch8/QUSBEM_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUSBEM_charged_5.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch8/QUSBEM_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUSBEM_charged_5.3.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch8/ORAGEU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ORAGEU_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch8/ORAGEU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ORAGEU_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch8/ULOKUD01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKUD01_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch8/FAVDEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDEO_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch8/FAVDEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDEO_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch8/ULOKUD01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKUD01_clean_1.2.1_473.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/ULOLUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLUE_clean_1.1.4_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/ULOLUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLUE_clean_1.1.4_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/ic5b00096_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ic5b00096_auto_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/ic5b00096_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ic5b00096_auto_1.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/COQJID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_COQJID_clean_3.1.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/COQJID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_COQJID_clean_3.1.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/JALTUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JALTUL_clean_2.3.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/JALTUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JALTUL_clean_2.3.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/ZITRUP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZITRUP_clean_3.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/ZITRUP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZITRUP_clean_3.3.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/XIGHEB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIGHEB_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch34/XIGHEB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIGHEB_clean_1.2.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/SACDUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SACDUX_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/SACDUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SACDUX_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/HAPBEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HAPBEI_clean_3.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/HAPBEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HAPBEI_clean_3.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/IYOCIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IYOCIK_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/IYOCIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IYOCIK_clean_1.2.1_473.000000_10000.data




Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/TURBUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TURBUE_clean_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/TURBUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TURBUE_clean_2.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/VUHMOC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHMOC_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch15/VUHMOC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHMOC_clean_1.2.1_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch4/RUBLEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch4/RUBLEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch4/cg501730q_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_cg501730q_si_002_clean_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch4/cg501730q_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_cg501730q_si_002_clean_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch4/HOYREU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYREU_clean_2.2.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch4/HOYREU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYREU_clean_2.2.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch4/ja512311a_si_003_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512311a_si_003_auto_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch4/ja512311a_si_003_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512311a_si_003_auto_1.1.1_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/ZUCKIT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/ZUCKIT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/CIXBUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIXBUH_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/ENAFOP_ion_b/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ENAFOP_ion_b_2.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/ENAFOP_ion_b/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ENAFOP_ion_b_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/CIXBUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIXBUH_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/XAPDAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPDAU_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/XAPDAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPDAU_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/GUVLAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUVLAL_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/GUVLAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUVLAL_clean_2.1.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/OVADAR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OVADAR_clean_4.4.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/OVADAR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OVADAR_clean_4.4.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/SOXHUI_SL/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOXHUI_SL_2.2.5_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/SOXHUI_SL/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOXHUI_SL_2.2.5_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/PORLEP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_PORLEP_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/PORLEP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_PORLEP_clean_2.1.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/FUBDEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FUBDEM_clean_2.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch18/FUBDEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FUBDEM_clean_2.1.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/NIVWIY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NIVWIY_clean_6.4.4_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/NIVWIY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NIVWIY_clean_6.4.4_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/ISUGIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ISUGIN_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/YEZSEC01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_YEZSEC01_clean_1.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/ISUGIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ISUGIN_clean_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/YEZSEC01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_YEZSEC01_clean_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/VAKPUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKPUV_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/VAKPUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKPUV_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/ICITUK_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ICITUK_charged_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/ICITUK_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ICITUK_charged_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/LUDVEL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVEL_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/LUDVEL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVEL_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/WEFZIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WEFZIS_clean_4.4.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch39/WEFZIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WEFZIS_clean_4.4.2_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/SEHMUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SEHMUO_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/UDAWUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAWUU_clean_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/SEHMUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SEHMUO_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/UDAWUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAWUU_clean_2.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/HAPBAE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HAPBAE_clean_3.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/HAPBAE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HAPBAE_clean_3.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/TISWEZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TISWEZ_clean_3.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/TISWEZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TISWEZ_clean_3.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/ZEZPIF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZEZPIF_clean_2.3.3_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/ZEZPIF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZEZPIF_clean_2.3.3_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/FANDEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FANDEG_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/FANDEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FANDEG_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/GOYXID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GOYXID_clean_3.3.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch13/GOYXID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GOYXID_clean_3.3.2_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/RIYBEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBEI_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/WODWUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WODWUJ_clean_3.3.3_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/WODWUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WODWUJ_clean_3.3.3_473.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/RIYBEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBEI_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/GARTAX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GARTAX_clean_3.3.3_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/GARTAX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GARTAX_clean_3.3.3_473.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/POKVAO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POKVAO_clean_5.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/POKVAO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POKVAO_clean_5.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/VOZVIR01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVIR01_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/VOZVIR01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVIR01_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/HABCEV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HABCEV_clean_1.1.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/HABCEV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HABCEV_clean_1.1.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/RIYBIM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBIM_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/RIYBIM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBIM_clean_2.1.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/QESYOD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QESYOD_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/QESYOD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QESYOD_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/VUHPUL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHPUL_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/VUHPUL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHPUL_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/ULOLEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLEO_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch20/ULOLEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLEO_clean_1.2.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/XOMJOY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XOMJOY_clean_3.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/XOMJOY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XOMJOY_clean_3.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/WUDZUS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZUS_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/WUDZUS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZUS_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/XUNHAQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNHAQ_clean_5.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/XIGHAX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XIGHAX_clean_2.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/XUNHAQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNHAQ_clean_5.3.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/XIGHAX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XIGHAX_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/CUVHIL02_clean_h/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL02_clean_h_3.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/CUVHIL02_clean_h/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL02_clean_h_3.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/LABPEM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABPEM_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch26/LABPEM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABPEM_clean_1.2.1_473.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/IMUKUW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/IMUKUW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/AMUWIP_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AMUWIP_charged_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/LIKCOY_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIKCOY_charged_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/AMUWIP_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AMUWIP_charged_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/LIKCOY_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIKCOY_charged_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/AGABIU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AGABIU_clean_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/AGABIU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AGABIU_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/ja512973b_si_002_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_002_auto_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/ja512973b_si_002_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_002_auto_2.2.2_473.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/ZIHTEP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZIHTEP_clean_4.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/ZIHTEP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZIHTEP_clean_4.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/LABNOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNOU_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/LABNOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNOU_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/WUDYUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDYUR_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/WUDYUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDYUR_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/CIXCAO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIXCAO_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/CIXCAO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIXCAO_clean_2.1.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/LABQAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABQAJ_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch21/LABQAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABQAJ_clean_1.2.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/UCOJED_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJED_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/NIFZOT_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NIFZOT_charged_2.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/NIFZOT_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NIFZOT_charged_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/UCOJED_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJED_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/NARPAA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NARPAA_clean_3.2.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/NARPAA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NARPAA_clean_3.2.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/UVUQOT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UVUQOT_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/UVUQOT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UVUQOT_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/NEGMUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_NEGMUI_clean_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/NEGMUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_NEGMUI_clean_2.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/CAYMIZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAYMIZ_clean_4.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/CAYMIZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAYMIZ_clean_4.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/HOYRIY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYRIY_clean_2.2.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch6/HOYRIY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYRIY_clean_2.2.3_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/RIVDEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/RIVDEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/ja512973b_si_004_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_004_auto_1.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/ja512973b_si_004_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_004_auto_1.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/KACGAZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KACGAZ_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/KACGAZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KACGAZ_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/REXCEE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCEE_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/REXCEE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCEE_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/GEVXIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GEVXIQ_clean_3.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/GEVXIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GEVXIQ_clean_3.3.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/WUDZIG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZIG_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch29/WUDZIG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZIG_clean_1.2.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/DAMDUT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DAMDUT_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/LUDTUZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDTUZ_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/DAMDUT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DAMDUT_clean_1.2.1_473.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/VAKPOP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKPOP_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/LUDTUZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDTUZ_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/VAKPOP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKPOP_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/LABNEK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNEK_clean_1.2.1_473.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/LABNEK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNEK_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/CAKFEB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAKFEB_clean_3.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/CAKFEB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAKFEB_clean_3.2.2_473.000000_100000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/UCOJIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOJIH_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/UCOJIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOJIH_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/KODPUP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KODPUP_clean_2.4.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/VUHPOF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHPOF_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch40/VUHPOF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHPOF_clean_1.2.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/RAKDEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAKDEN_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/RAKDEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAKDEN_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/RAKDAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAKDAJ_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/BUPFEY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_BUPFEY_clean_1.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/SOMCON_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOMCON_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/SOMCON_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOMCON_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/BUPFEY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BUPFEY_clean_1.1.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/RAKDAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAKDAJ_clean_1.2.1_473.000000_10000.data




Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/LABMUZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABMUZ_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/LABMUZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABMUZ_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/JEDJUY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JEDJUY_clean_4.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/JEDJUY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JEDJUY_clean_4.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/CIPLIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIPLIX_clean_2.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/CIPLIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIPLIX_clean_2.3.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/VIZSOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZSOO_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/VIZSOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZSOO_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/REXCUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCUU_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/REXCUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCUU_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/QOGGID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOGGID_clean_4.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch7/QOGGID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOGGID_clean_4.2.2_473.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/OCUNAC_manual/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/OCUNAC_manual/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/REXFOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFOR_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/REXFOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFOR_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/POFGUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_POFGUO_clean_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/POFGUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_POFGUO_clean_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/RUBTAK03_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RUBTAK03_auto_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/RUBTAK03_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RUBTAK03_auto_2.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/CEDFIC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CEDFIC_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/UTOCAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UTOCAJ_clean_3.3.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/UTOCAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UTOCAJ_clean_3.3.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/CEDFIC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CEDFIC_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/DOGMET_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DOGMET_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/DOGMET_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DOGMET_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/QETCUO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QETCUO_clean_3.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/SOHMEI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMEI_clean_2.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/SOHMEI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMEI_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch37/QETCUO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QETCUO_clean_3.3.3_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/REXDAB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDAB_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/REXDAB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDAB_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/GEGBOL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GEGBOL_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/EBEXIU02_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXIU02_clean_3.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/EBEXIU02_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXIU02_clean_3.3.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/GEGBOL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GEGBOL_clean_2.1.1_473.000000_100000.data





Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/FOFMOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FOFMOE_clean_3.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/FOFMOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FOFMOE_clean_3.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/OSIKIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OSIKIL_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/OSIKIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OSIKIL_clean_2.1.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/DEFRIR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DEFRIR_clean_3.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/RIYBOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBOS_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/DEFRIR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DEFRIR_clean_3.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/RIYBOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBOS_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/ja512311a_si_007_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512311a_si_007_auto_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch14/ja512311a_si_007_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512311a_si_007_auto_1.1.1_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/LAFRAN01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/LAFRAN01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/ULOJUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOJUC_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/XEGKUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XEGKUR_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/JOVROD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_JOVROD_clean_3.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/ULOJUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOJUC_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/XEGKUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XEGKUR_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/jacs.5b12516_ja5b12516_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_002_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/jacs.5b12516_ja5b12516_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_002_clean_2.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/JOVROD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_JOVROD_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/ja5b00450_si_006_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja5b00450_si_006_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/RIHXIR_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIHXIR_charged_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch44/RIHXIR_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIHXIR_charged_2.2.2_473.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/ZISXEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISXEG_clean_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/XAPDEY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPDEY_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/REXFUX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFUX_clean_2.2.1_473.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/XAPDEY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPDEY_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/HUCBAJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HUCBAJ_charged_3.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/HUCBAJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HUCBAJ_charged_3.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/ZISXEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISXEG_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/REXFUX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFUX_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/REXCII_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXCII_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/REXCII_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXCII_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/acs.inorgchem.6b02407_ic6b02407_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_003_clean_2.2.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/acs.inorgchem.6b02407_ic6b02407_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_acs.inorgchem.6b02407_ic6b02407_si_003_clean_2.2.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/CUVHIL_clean_h/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL_clean_h_3.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/CUVHIL_clean_h/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL_clean_h_3.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/ja507947d_si_001_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja507947d_si_001_auto_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/ja507947d_si_001_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja507947d_si_001_auto_1.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/GUSCIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_GUSCIH_clean_3.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch31/GUSCIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_GUSCIH_clean_3.3.3_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/VUJBOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/VUJBOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/SARMII_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SARMII_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/QARLON_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QARLON_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/SARMII_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SARMII_clean_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/VUHNIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNIX_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/MEXJAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MEXJAC_clean_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/LAKFIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LAKFIN_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/LAKFIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LAKFIN_clean_2.1.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/MEXJAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MEXJAC_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/QARLON_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QARLON_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/VUHNIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNIX_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/SUXGUP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SUXGUP_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/SUXGUP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SUXGUP_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/QOJTUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOJTUE_clean_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/QOJTUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOJTUE_clean_2.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/VOZVAJ01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVAJ01_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/VOZVAJ01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVAJ01_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/ZOQSUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQSUV_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/ZOQSUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQSUV_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/VUHPAR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHPAR_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/VUHPAR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHPAR_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/LABQEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABQEN_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch12/LABQEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABQEN_clean_1.2.1_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/XITYEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/XITYEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/OJOZOE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OJOZOE_clean_5.4.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/OJOZOE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OJOZOE_clean_5.4.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/TEJGEW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TEJGEW_clean_3.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/TEJGEW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TEJGEW_clean_3.3.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/DOMGAP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DOMGAP_clean_1.1.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/DOMGAP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DOMGAP_clean_1.1.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/QARMAA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QARMAA_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/QARMAA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QARMAA_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/AKUHOD01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_AKUHOD01_clean_4.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch10/AKUHOD01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_AKUHOD01_clean_4.3.3_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/OKUJUB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/OKUJUB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/QOJVAM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QOJVAM_clean_3.3.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/ZISYAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISYAD_clean_4.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/QOJVAM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QOJVAM_clean_3.3.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/ZISYAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISYAD_clean_4.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/LOCNIB_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LOCNIB_clean_3.3.3_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/LOCNIB_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LOCNIB_clean_3.3.3_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/ja500330a_si_009_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja500330a_si_009_auto_1.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/ja500330a_si_009_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja500330a_si_009_auto_1.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/IFEPIT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IFEPIT_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/IFEPIT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IFEPIT_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/FITJAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FITJAU_clean_3.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch11/FITJAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FITJAU_clean_3.2.2_473.000000_100000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/RIVDIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/RIVDIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/XICYUF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/XICYUF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/LABMOT_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABMOT_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/LABMOT_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABMOT_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/REXFEH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFEH_clean_2.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/REXFEH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFEH_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/VARWUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VARWUI_clean_3.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/VARWUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VARWUI_clean_3.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/TUZVUH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TUZVUH_clean_4.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch41/TUZVUH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TUZVUH_clean_4.2.2_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch36/ja6b00695_si_001_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch36/ja6b00695_si_001_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch36/VIZTIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZTIJ_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch36/VIZTIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZTIJ_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch36/XISDOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XISDOU_clean_1.3.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch36/XISDOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XISDOU_clean_1.3.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch36/FOPTOU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FOPTOU_clean_2.1.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch36/FOPTOU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FOPTOU_clean_2.1.2_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/QAFDOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/QAFDOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/LABNAG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNAG_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/LABNAG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNAG_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/FUBDIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FUBDIQ_clean_2.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/TASWER_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TASWER_clean_2.1.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/TASWER_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TASWER_clean_2.1.2_473.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/FUBDIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FUBDIQ_clean_2.1.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/LIXXAS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXXAS_clean_3.3.3_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/LIXXAS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXXAS_clean_3.3.3_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/UDAXEF_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAXEF_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/UDAXEF_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAXEF_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/VUHNUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNUJ_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/VUHNUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNUJ_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/ERIRIG_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ERIRIG_auto_1.1.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch42/ERIRIG_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ERIRIG_auto_1.1.1_473.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/VOBGAW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOBGAW_clean_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/LIXXEW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LIXXEW_clean_3.3.3_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/LIXXEW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LIXXEW_clean_3.3.3_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/HOZFIN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOZFIN_clean_2.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/HOZFIN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOZFIN_clean_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/VOBGAW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOBGAW_clean_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/IYOCOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IYOCOQ_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/IYOCOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IYOCOQ_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/LUDVAH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVAH_clean_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/LUDVAH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVAH_clean_2.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/VOQXIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOQXIK_clean_2.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/VOQXIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOQXIK_clean_2.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/QUPDEL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUPDEL_clean_4.4.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/QUPDEL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUPDEL_clean_4.4.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/ZOQTAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZOQTAC_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/ZOQTAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZOQTAC_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/VIZSUU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VIZSUU_clean_1.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/VIZSUU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VIZSUU_clean_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/LUDVOV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUDVOV_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/LUDVOV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUDVOV_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/OGOJOJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_OGOJOJ_charged_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/OGOJOJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_OGOJOJ_charged_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/ja4050828_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja4050828_auto_1.1.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch27/ja4050828_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja4050828_auto_1.1.2_473.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/ADEGIA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ADEGIA_clean_4.3.3_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/ADEGIA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ADEGIA_clean_4.3.3_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/UKAQIH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UKAQIH_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/UKAQIH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UKAQIH_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/LABNUA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABNUA_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/LABNUA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABNUA_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/RAVDID_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAVDID_clean_3.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/RAVDID_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAVDID_clean_3.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/INOVEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_INOVEN_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch3/INOVEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_INOVEN_clean_2.2.2_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/HANKIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/HANKIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/LABJUV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LABJUV_clean_3.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/ALULAV_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ALULAV_clean_2.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/LABJUV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LABJUV_clean_3.3.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/ALULAV_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ALULAV_clean_2.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/UBULUA_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UBULUA_clean_2.1.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/UBULUA_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UBULUA_clean_2.1.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/SOHNEJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHNEJ_clean_2.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/SOHNEJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHNEJ_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/SUKKOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SUKKOZ_clean_3.2.4_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/REXDIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXDIJ_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/REXDIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXDIJ_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/SUKKOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SUKKOZ_clean_3.2.4_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/VUHMUI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHMUI_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/VUHMUI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHMUI_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/KOBPUN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KOBPUN_clean_4.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/KOBPUN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KOBPUN_clean_4.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/ULOKOX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKOX_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/ULOKOX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKOX_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/EPUVAN_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EPUVAN_charged_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch30/EPUVAN_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EPUVAN_charged_2.2.2_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/WIYWOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIYWOS_clean_3.1.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/WIYWOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIYWOS_clean_3.1.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/CIWSAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWSAD_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/CIWSAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWSAD_clean_2.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/ULOLIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLIS_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/ULOLIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLIS_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/VOZVEN01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VOZVEN01_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/VOZVEN01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VOZVEN01_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/XULVAD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XULVAD_clean_4.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch22/XULVAD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XULVAD_clean_4.3.2_473.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/QUPDEL01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QUPDEL01_clean_3.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/QUPDEL01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QUPDEL01_clean_3.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/CIWRUW_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWRUW_clean_2.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/CIWRUW_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWRUW_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/ULOJUC01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOJUC01_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/ULOJUC01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOJUC01_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/WIHTAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIHTAK_clean_4.2.4_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/WIHTAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIHTAK_clean_4.2.4_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/EBEXEQ01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_EBEXEQ01_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/EBEXEQ01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_EBEXEQ01_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/ja512973b_si_003_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja512973b_si_003_auto_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/ja512973b_si_003_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja512973b_si_003_auto_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/XAPTUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XAPTUE_clean_3.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/XAPTUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XAPTUE_clean_3.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/KOJZOZ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_KOJZOZ_clean_1.1.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/KOJZOZ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_KOJZOZ_clean_1.1.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/ZISXOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZISXOQ_clean_3.1.3_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/ZISXOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZISXOQ_clean_3.1.3_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/jacs.5b12516_ja5b12516_si_004_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_004_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch23/jacs.5b12516_ja5b12516_si_004_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_jacs.5b12516_ja5b12516_si_004_clean_2.2.2_473.000000_10000.data
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch33/HANKUE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch33/HANKUE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch33/DUZKAM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_DUZKAM_clean_1.1.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch33/DUZKAM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_DUZKAM_clean_1.1.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch33/UDAXIJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAXIJ_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch33/UDAXIJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAXIJ_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch33/PEFRUP01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_PEFRUP01_clean_3.1.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch33/PEFRUP01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_PEFRUP01_clean_3.1.2_473.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/HANKOY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/HANKOY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/UCOHUR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UCOHUR_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/UCOHUR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UCOHUR_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/SOHMOS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMOS_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/SOHMOS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMOS_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/XUNSOQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNSOQ_clean_5.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/XUNSOQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNSOQ_clean_5.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/CUVHIL01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CUVHIL01_clean_3.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/CUVHIL01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CUVHIL01_clean_3.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/ZEZQEC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ZEZQEC_clean_3.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/ZEZQEC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ZEZQEC_clean_3.3.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/UTOCEN_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UTOCEN_clean_3.3.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch24/UTOCEN_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UTOCEN_clean_3.3.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch43/ja0752540-file002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja0752540-file002_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch43/ja0752540-file002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja0752540-file002_clean_2.1.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch43/REXFIL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_REXFIL_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch43/REXFIL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_REXFIL_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch43/CIWROQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWROQ_clean_2.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch43/CIWROQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWROQ_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch43/RONCIG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RONCIG_clean_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch43/RONCIG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RONCIG_clean_2.2.2_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch1/HOYROE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_HOYROE_clean_3.1.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch1/HOYROE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_HOYROE_clean_3.1.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch1/FAVDIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FAVDIS_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch1/FAVDIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FAVDIS_clean_1.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch1/VAKQAC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VAKQAC_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch1/VAKQAC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VAKQAC_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch1/IWEWAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEWAK_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch1/IWEWAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEWAK_clean_1.2.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/LUWNAU_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_LUWNAU_clean_1.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/LUWNAU_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_LUWNAU_clean_1.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/WIKXUJ_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WIKXUJ_charged_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/WIKXUJ_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WIKXUJ_charged_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/CAKFEB01_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CAKFEB01_clean_2.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/CAKFEB01_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CAKFEB01_clean_2.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/QISNIR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QISNIR_clean_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/QISNIR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QISNIR_clean_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/IWEVUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEVUD_clean_1.2.1_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/IWEVUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEVUD_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/IPEBAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IPEBAI_clean_2.2.1_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/IPEBAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IPEBAI_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/RIYBAE_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RIYBAE_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch16/RIYBAE_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RIYBAE_clean_1.2.1_473.000000_100000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/SACDOR_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SACDOR_clean_2.1.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/SACDOR_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SACDOR_clean_2.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/BIFGOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_BIFGOO_clean_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/BIFGOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_BIFGOO_clean_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/CIWREG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWREG_clean_2.1.1_473.000000_10000.data



Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/CIWREG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWREG_clean_2.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/IWEWIS_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IWEWIS_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/IWEWIS_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IWEWIS_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/WUDZAY_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_WUDZAY_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/WUDZAY_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_WUDZAY_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/ODEKAL_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ODEKAL_clean_4.3.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/ODEKAL_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ODEKAL_clean_4.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/ja5b02777_si_003_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja5b02777_si_003_clean_3.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/ja5b02777_si_003_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja5b02777_si_003_clean_3.3.3_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/MUBZUG_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MUBZUG_auto_2.2.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/MUBZUG_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MUBZUG_auto_2.2.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/UDAWOO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UDAWOO_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch5/UDAWOO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UDAWOO_clean_1.2.1_473.000000_10000.data

No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/HANKEO_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar
No valid results found in:
CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/HANKEO_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/ULOLAK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOLAK_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/ULOLAK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOLAK_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/ULOKUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKUD_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/ULOKUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKUD_clean_1.2.1_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/MUBZOA_auto/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_MUBZOA_auto_2.2.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/MUBZOA_auto/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_MUBZOA_auto_2.2.2_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/XUNGUJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XUNGUJ_clean_5.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/XUNGUJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XUNGUJ_clean_5.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/UMEDOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_UMEDOH_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/UMEDOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_UMEDOH_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/COKJIX_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_COKJIX_clean_4.3.2_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/COKJIX_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_COKJIX_clean_4.3.2_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/ja5b02777_si_002_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ja5b02777_si_002_clean_3.3.3_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch17/ja5b02777_si_002_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ja5b02777_si_002_clean_3.3.3_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/CURBOH_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CURBOH_clean_2.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/CURBOH_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CURBOH_clean_2.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/QAWRIQ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_QAWRIQ_clean_3.3.3_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/QAWRIQ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_QAWRIQ_clean_3.3.3_473.000000_10000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/ULOKAJ_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_ULOKAJ_clean_1.2.1_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/ULOKAJ_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_ULOKAJ_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/TAMZUE_charged/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_TAMZUE_charged_3.3.2_473.000000_100000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/TAMZUE_charged/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_TAMZUE_charged_3.3.2_473.000000_10000.data


Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/VUHNAP_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_VUHNAP_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/VUHNAP_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_VUHNAP_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/XOFGEG_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_XOFGEG_clean_1.1.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/XOFGEG_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_XOFGEG_clean_1.1.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/CIWRIK_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_CIWRIK_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch0/CIWRIK_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_CIWRIK_clean_1.2.1_473.000000_10000.data

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch9/IXISUD_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_IXISUD_clean_2.2.2_473.000000_10000.dataFound wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch9/IXISUD_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_IXISUD_clean_2.2.2_473.000000_100000.data

Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch9/RAKCUC_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_RAKCUC_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch9/RAKCUC_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_RAKCUC_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch9/SOHMIM_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_SOHMIM_clean_1.2.1_473.000000_10000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch9/SOHMIM_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_SOHMIM_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch9/FUBDAI_clean/Adsorption_CO2_N2_0.150_0.850_1.000bar/Output/System_0/output_FUBDAI_clean_1.2.1_473.000000_100000.data
Found wrong simulation result in CGCNN_MT/inference/CoREMOF2019/stable_coremof_4606_mc473.0K/mc_data/batch9/FUBDAI_clean/Adsorption_CO2_N2_0.150_0.850_0.100bar/Output/System_0/output_FUBDAI_clean_1.2.1_473.000000_10000.data
number of isotherm data points:  17130

/home/zhangsd/repos/CF-BGAP/GCMC/utils.py:782: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

In [8]:
root_dir = Path(f"CGCNN_MT/inference/CoREMOF2019")
ads_all = []
valid_cols = ["MofName"]
mix_frac = [0.15, 0.85]
ads_keys = []
for p in [0.1, 1]:
    for gas in ["CO2", "N2"]:
        for temp in [298.0, 323.0, 473.0]:
            dataset = f"stable_coremof_4606_mc{temp}K"
            df_ads = pd.read_csv(root_dir/dataset/'mc_data'/f'00-isotherm-data-{dataset}.tsv', sep='\t')
            ads_col_mix = f"Ads{gas}_{temp}K_{p}bar_mix{mix_frac[0]}"
            ads_col_pure = f"Ads{gas}_{temp}K_{p}bar_pure"

            sub_df_mix = df_ads[(df_ads["Pressure[bar]"]==p)&(df_ads["MoleculeFraction"].isin(mix_frac))&(df_ads["GasName"]==gas)]
            sub_df_pure = df_ads[(df_ads["Pressure[bar]"]==p)&(df_ads["MoleculeFraction"].isin([0, 1]))&(df_ads["GasName"]==gas)]
            sub_df_mix = sub_df_mix.rename(columns={"ExcessLoading": ads_col_mix})
            sub_df_pure = sub_df_pure.rename(columns={"ExcessLoading": ads_col_pure})
            sub_df_merge = pd.merge(sub_df_mix[valid_cols+[ads_col_mix]], 
                                    sub_df_pure[valid_cols+[ads_col_pure]], on=["MofName"], how="outer")
            ads_all.append(sub_df_merge)
            ads_keys.append(ads_col_mix)
            ads_keys.append(ads_col_pure)
ads_all_df = ads_all[0]
for i in range(1, len(ads_all)):
    ads_all_df = pd.merge(ads_all_df, ads_all[i], on=["MofName"], how="outer")
print(ads_all_df.shape)
ads_all_df

(4285, 25)

,MofName,AdsCO2_298.0K_0.1bar_mix0.15,AdsCO2_298.0K_0.1bar_pure,AdsCO2_323.0K_0.1bar_mix0.15,AdsCO2_323.0K_0.1bar_pure,AdsCO2_473.0K_0.1bar_mix0.15,AdsCO2_473.0K_0.1bar_pure,AdsN2_298.0K_0.1bar_mix0.15,AdsN2_298.0K_0.1bar_pure,AdsN2_323.0K_0.1bar_mix0.15,...,AdsCO2_323.0K_1bar_mix0.15,AdsCO2_323.0K_1bar_pure,AdsCO2_473.0K_1bar_mix0.15,AdsCO2_473.0K_1bar_pure,AdsN2_298.0K_1bar_mix0.15,AdsN2_298.0K_1bar_pure,AdsN2_323.0K_1bar_mix0.15,AdsN2_323.0K_1bar_pure,AdsN2_473.0K_1bar_mix0.15,AdsN2_473.0K_1bar_pure
0,1499489-acs.cgd.6b01265_1499490_clean,0.240434,NaN,0.109068,NaN,0.005482,NaN,0.070534,NaN,0.044157,...,0.964793,NaN,0.053929,NaN,0.509938,NaN,0.355527,NaN,0.055893,NaN
1,ABIYIV_clean,0.125825,NaN,0.050572,NaN,0.001256,NaN,0.017306,NaN,0.010439,...,0.364025,NaN,0.011850,NaN,0.101088,NaN,0.071616,NaN,0.002280,NaN
2,ABULOB_clean,1.082917,NaN,0.429902,NaN,0.009443,NaN,0.158583,NaN,0.095937,...,2.503685,NaN,0.089549,NaN,0.421389,NaN,0.458533,NaN,0.066999,NaN
3,ABUWOJ_clean,0.163324,NaN,0.069820,NaN,0.002972,NaN,0.038033,NaN,0.022945,...,0.646815,NaN,0.030947,NaN,0.298711,NaN,0.196348,NaN,0.023749,NaN
4,ACAJIY_clean,0.152653,NaN,0.058717,NaN,0.001507,NaN,0.039470,NaN,0.021980,...,0.518287,NaN,0.015216,NaN,0.302958,NaN,0.187103,NaN,0.010326,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4280,magnetochemistry3010001_PF362NdCl_clean,3.834589,NaN,3.864262,NaN,3.275996,NaN,-0.001131,NaN,-0.001009,...,3.844993,NaN,3.544294,NaN,0.016758,NaN,0.017477,NaN,-0.007086,NaN
4281,nchem.2258-s3_clean,NaN,NaN,0.044483,NaN,0.003332,NaN,NaN,NaN,0.028499,...,0.408305,NaN,0.034366,NaN,NaN,NaN,0.256822,NaN,0.051179,NaN
4282,ncomms11831_ncomms11831-s2_clean,0.950713,NaN,0.497151,NaN,0.007881,NaN,0.061307,NaN,0.053646,...,1.172071,NaN,0.076844,NaN,0.067538,NaN,0.105436,NaN,0.035601,NaN
4283,ncomms11831_ncomms11831-s3_clean,0.725134,NaN,0.364229,NaN,0.006090,NaN,0.059856,NaN,0.045677,...,1.070984,NaN,0.057025,NaN,0.096040,NaN,0.119705,NaN,0.024964,NaN
4284,ncomms7350-s2_clean,0.058460,NaN,0.026893,NaN,0.001404,NaN,0.020010,NaN,0.011969,...,0.246240,NaN,0.015116,NaN,0.162371,NaN,0.108308,NaN,0.014718,NaN

In [5]:
ads_keys

['AdsCO2_298.0K_0.1bar_mix0.15',
 'AdsCO2_298.0K_0.1bar_pure',
 'AdsCO2_323.0K_0.1bar_mix0.15',
 'AdsCO2_323.0K_0.1bar_pure',
 'AdsCO2_473.0K_0.1bar_mix0.15',
 'AdsCO2_473.0K_0.1bar_pure',
 'AdsN2_298.0K_0.1bar_mix0.15',
 'AdsN2_298.0K_0.1bar_pure',
 'AdsN2_323.0K_0.1bar_mix0.15',
 'AdsN2_323.0K_0.1bar_pure',
 'AdsN2_473.0K_0.1bar_mix0.15',
 'AdsN2_473.0K_0.1bar_pure',
 'AdsCO2_298.0K_1bar_mix0.15',
 'AdsCO2_298.0K_1bar_pure',
 'AdsCO2_323.0K_1bar_mix0.15',
 'AdsCO2_323.0K_1bar_pure',
 'AdsCO2_473.0K_1bar_mix0.15',
 'AdsCO2_473.0K_1bar_pure',
 'AdsN2_298.0K_1bar_mix0.15',
 'AdsN2_298.0K_1bar_pure',
 'AdsN2_323.0K_1bar_mix0.15',
 'AdsN2_323.0K_1bar_pure',
 'AdsN2_473.0K_1bar_mix0.15',
 'AdsN2_473.0K_1bar_pure']

In [9]:
col_list = [
    'MofName',
    'AdsCO2_323.0K_0.1bar_mix0.15',
    'AdsCO2_323.0K_0.1bar_pure',
    'AdsCO2_473.0K_0.1bar_mix0.15',
    'AdsCO2_473.0K_0.1bar_pure',
    'AdsN2_323.0K_0.1bar_mix0.15',
    'AdsN2_323.0K_0.1bar_pure',
    'AdsN2_473.0K_0.1bar_mix0.15',
    'AdsN2_473.0K_0.1bar_pure',
    'AdsCO2_323.0K_1bar_mix0.15',
    'AdsCO2_323.0K_1bar_pure',
    'AdsCO2_473.0K_1bar_mix0.15',
    'AdsCO2_473.0K_1bar_pure',
    'AdsN2_323.0K_1bar_mix0.15',
    'AdsN2_323.0K_1bar_pure',
    'AdsN2_473.0K_1bar_mix0.15',
    'AdsN2_473.0K_1bar_pure'
    ]

new_col_list = [
    ]
for p in ['1bar']:
    for m in ['mix0.15']:
        for t in ['323.0K', '473.0K']:
            ads_all_df[f"S_{t}_{p}_{m}"] = ads_all_df[f'AdsCO2_{t}_{p}_{m}']/(ads_all_df[f'AdsN2_{t}_{p}_{m}']+1e-10)
            new_col_list.append(f"S_{t}_{p}_{m}")

for gas in ['CO2', 'N2']:
    for m in ['mix0.15']:
        ads_all_df[f"WC_{gas}_{m}"] = ads_all_df[f'Ads{gas}_323.0K_1bar_{m}']-ads_all_df[f'Ads{gas}_473.0K_1bar_{m}']
        new_col_list.append(f"WC_{gas}_{m}")

ads_all_df = ads_all_df.reindex(columns=col_list[0:1] + new_col_list + col_list[1:])
col_list

['MofName',
 'AdsCO2_323.0K_0.1bar_mix0.15',
 'AdsCO2_323.0K_0.1bar_pure',
 'AdsCO2_473.0K_0.1bar_mix0.15',
 'AdsCO2_473.0K_0.1bar_pure',
 'AdsN2_323.0K_0.1bar_mix0.15',
 'AdsN2_323.0K_0.1bar_pure',
 'AdsN2_473.0K_0.1bar_mix0.15',
 'AdsN2_473.0K_0.1bar_pure',
 'AdsCO2_323.0K_1bar_mix0.15',
 'AdsCO2_323.0K_1bar_pure',
 'AdsCO2_473.0K_1bar_mix0.15',
 'AdsCO2_473.0K_1bar_pure',
 'AdsN2_323.0K_1bar_mix0.15',
 'AdsN2_323.0K_1bar_pure',
 'AdsN2_473.0K_1bar_mix0.15',
 'AdsN2_473.0K_1bar_pure']

In [ ]:
# col_list = [
#     'MofName',
#     'AdsCO2_298.0K_0.1bar_mix0.15',
#     'AdsCO2_298.0K_0.1bar_pure',
#     'AdsCO2_473.0K_0.1bar_mix0.15',
#     'AdsCO2_473.0K_0.1bar_pure',
#     'AdsN2_298.0K_0.1bar_mix0.15',
#     'AdsN2_298.0K_0.1bar_pure',
#     'AdsN2_473.0K_0.1bar_mix0.15',
#     'AdsN2_473.0K_0.1bar_pure',
#     'AdsCO2_298.0K_1bar_mix0.15',
#     'AdsCO2_298.0K_1bar_pure',
#     'AdsCO2_473.0K_1bar_mix0.15',
#     'AdsCO2_473.0K_1bar_pure',
#     'AdsN2_298.0K_1bar_mix0.15',
#     'AdsN2_298.0K_1bar_pure',
#     'AdsN2_473.0K_1bar_mix0.15',
#     'AdsN2_473.0K_1bar_pure'
#     ]
# new_col_list = [
#     ]
# for p in ['1bar']:
#     for m in ['mix0.15']:
#         for t in ['298.0K', '473.0K']:
#             ads_all_df[f"S_{t}_{p}_{m}"] = ads_all_df[f'AdsCO2_{t}_{p}_{m}']/(ads_all_df[f'AdsN2_{t}_{p}_{m}']+1e-10)
#             new_col_list.append(f"S_{t}_{p}_{m}")

# for gas in ['CO2', 'N2']:
#     for m in ['mix0.15']:
#         ads_all_df[f"WC_{gas}_{m}"] = ads_all_df[f'Ads{gas}_298.0K_1bar_{m}']-ads_all_df[f'Ads{gas}_473.0K_1bar_{m}']
#         new_col_list.append(f"WC_{gas}_{m}")

# ads_all_df = ads_all_df.reindex(columns=col_list[0:1] + new_col_list + col_list[1:])
# col_list

['MofName',
 'AdsCO2_293.0K_0.1bar_mix0.15',
 'AdsCO2_293.0K_0.1bar_pure',
 'AdsCO2_473.0K_0.1bar_mix0.15',
 'AdsCO2_473.0K_0.1bar_pure',
 'AdsN2_293.0K_0.1bar_mix0.15',
 'AdsN2_293.0K_0.1bar_pure',
 'AdsN2_473.0K_0.1bar_mix0.15',
 'AdsN2_473.0K_0.1bar_pure',
 'AdsCO2_293.0K_1bar_mix0.15',
 'AdsCO2_293.0K_1bar_pure',
 'AdsCO2_473.0K_1bar_mix0.15',
 'AdsCO2_473.0K_1bar_pure',
 'AdsN2_293.0K_1bar_mix0.15',
 'AdsN2_293.0K_1bar_pure',
 'AdsN2_473.0K_1bar_mix0.15',
 'AdsN2_473.0K_1bar_pure']

In [10]:
ads_all_df.sort_values(by=['WC_CO2_mix0.15'], ascending=False)

,MofName,S_323.0K_1bar_mix0.15,S_473.0K_1bar_mix0.15,WC_CO2_mix0.15,WC_N2_mix0.15,AdsCO2_323.0K_0.1bar_mix0.15,AdsCO2_323.0K_0.1bar_pure,AdsCO2_473.0K_0.1bar_mix0.15,AdsCO2_473.0K_0.1bar_pure,AdsN2_323.0K_0.1bar_mix0.15,...,AdsN2_473.0K_0.1bar_mix0.15,AdsN2_473.0K_0.1bar_pure,AdsCO2_323.0K_1bar_mix0.15,AdsCO2_323.0K_1bar_pure,AdsCO2_473.0K_1bar_mix0.15,AdsCO2_473.0K_1bar_pure,AdsN2_323.0K_1bar_mix0.15,AdsN2_323.0K_1bar_pure,AdsN2_473.0K_1bar_mix0.15,AdsN2_473.0K_1bar_pure
2758,SARPIL_clean,289.675666,18.310633,13.366539,-0.025277,10.090787,NaN,0.171444,NaN,0.034679,...,0.008911,NaN,14.762538,NaN,1.395999,NaN,0.050962,NaN,0.076240,NaN
1041,HAFQUC_clean,97.074206,6.549728,8.718631,0.040452,3.946638,NaN,0.039181,NaN,0.040298,...,0.005733,NaN,9.065333,NaN,0.346702,NaN,0.093386,NaN,0.052934,NaN
3334,VUWROW_clean,133.940516,72.448146,8.637654,0.037270,9.761301,NaN,3.572422,NaN,0.078405,...,0.006183,NaN,12.932894,NaN,4.295241,NaN,0.096557,NaN,0.059287,NaN
4220,ja406030p_si_010_clean,24.951507,2.643728,7.954029,0.130803,3.884123,NaN,0.062492,NaN,0.207907,...,0.024883,NaN,8.509884,NaN,0.555854,NaN,0.341057,NaN,0.210254,NaN
1503,KEJQAR_clean,173.094154,13.832900,7.952899,-0.002699,6.622535,NaN,0.086361,NaN,0.017637,...,0.006153,NaN,8.684238,NaN,0.731339,NaN,0.050171,NaN,0.052869,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,KODPUP_clean,84.229089,NaN,NaN,NaN,5.676169,NaN,2.486531,NaN,0.093814,...,0.139965,NaN,6.535588,NaN,NaN,NaN,0.077593,NaN,NaN,NaN
1706,LEYYET_clean,NaN,-530.709516,NaN,NaN,3.382243,NaN,2.618048,NaN,-0.000884,...,-0.000434,NaN,NaN,NaN,2.982641,NaN,NaN,NaN,-0.005620,NaN
2259,OQUFAJ01_clean,NaN,16095.911447,NaN,NaN,17.206819,NaN,14.134222,NaN,0.000907,...,0.000829,NaN,NaN,NaN,15.397350,NaN,NaN,NaN,0.000957,NaN
2261,ORAQUU_clean,2229.496849,NaN,NaN,NaN,17.029651,NaN,11.827513,NaN,0.030431,...,0.137888,NaN,18.127593,NaN,NaN,NaN,0.008131,NaN,NaN,NaN
4241,ja5b00450_si_006_clean,NaN,17.481439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.892619,NaN,NaN,NaN,0.565893,NaN

In [12]:
ads_all_df.sort_values(by=['WC_CO2_mix0.15'], ascending=False).to_excel(root_dir/f"stable_coremof_4606_tsa_323K_473K.xlsx", index=False)